/**
 * CONTACT SOCKETS — named points on the body surface (docs/design/08 §5.7).
 *
 * A socket is a bone, a fraction along that bone, and an offset in the bone's
 * rest frame (identity-rest: the rest frame is model space, +Z front, +X the
 * fighter's left, Y up). Offsets are authored for MPFB's default body and are
 * scaled by the fighter's stature, so "the back of the neck" is on the back of
 * this fighter's neck whether he is 1.60 m or 2.00 m tall. Each socket also
 * carries an outward surface normal, which the hand solver uses to put the
 * palm on the surface rather than the wrist inside it.
 *
 * Sockets are written for the left side; `_R` variants are generated by
 * mirroring across X and swapping Left/Right bones.
 */
import { B, BONES, boneIndex, type RestSkeleton, type WorldPose } from '../../rig/skeleton';
import { add, getQ, getV3, lerp3, norm, qRot, scale, type V3 } from './math';

export interface SocketDef {
  bone: number;
  /** Fraction along the bone from head (0) to tail (1). */
  t: number;
  /** Offset in the bone's rest frame, metres on the reference body. */
  off: V3;
  /** Outward surface normal in the bone's rest frame. */
  n: V3;
}

type Row = [bone: string, t: number, off: V3, n: V3];

/** Symmetric sockets, left-side definition. */
const SIDED: Record<string, Row> = {
  head_side: ['Head', 0.45, [0.085, 0, 0.0], [1, 0, 0]],
  neck_side: ['Neck', 0.3, [0.06, 0, 0], [1, 0, 0]],
  // Shoulder top and hip hang off torso bones so that grabbing them does not
  // depend on how the partner's arm or leg is posed (no grip cycles).
  shoulder: ['LeftShoulder', 0.95, [0, 0.065, 0], [0, 1, 0]],
  armpit: ['LeftArm', 0.1, [0, -0.06, 0.0], [0, -1, 0]],
  bicep: ['LeftArm', 0.55, [0, 0, 0.045], [0, 0, 1]],
  tricep: ['LeftArm', 0.6, [0, 0, -0.045], [0, 0, -1]],
  elbow: ['LeftForeArm', 0.0, [0, 0, -0.035], [0, 0, -1]],
  elbow_inside: ['LeftForeArm', 0.03, [0, 0, 0.03], [0, 0, 1]],
  forearm: ['LeftForeArm', 0.5, [0, 0.035, 0], [0, 1, 0]],
  wrist: ['LeftForeArm', 0.88, [0, 0.03, 0], [0, 1, 0]],
  hand: ['LeftHand', 0.5, [0, 0.02, 0], [0, 1, 0]],
  chest: ['Spine2', 0.45, [0.09, 0, 0.1], [0.35, 0, 0.94]],
  ribs: ['Spine1', 0.6, [0.14, 0, 0.0], [1, 0, 0]],
  lat: ['Spine2', 0.15, [0.13, 0, -0.07], [0.7, 0, -0.7]],
  scap: ['Spine2', 0.6, [0.09, 0, -0.11], [0.2, 0, -0.98]],
  waist: ['Spine', 0.3, [0.14, 0, 0], [1, 0, 0]],
  hip: ['Hips', 0.0, [0.175, -0.035, 0.0], [1, 0, 0]],
  thigh: ['LeftUpLeg', 0.45, [0, 0, 0.075], [0, 0, 1]],
  thigh_in: ['LeftUpLeg', 0.4, [-0.065, 0, 0], [-1, 0, 0]],
  thigh_out: ['LeftUpLeg', 0.4, [0.075, 0, 0], [1, 0, 0]],
  thigh_back: ['LeftUpLeg', 0.5, [0, 0, -0.075], [0, 0, -1]],
  knee_front: ['LeftLeg', 0.0, [0, 0, 0.05], [0, 0, 1]],
  knee_back: ['LeftLeg', 0.06, [0, 0, -0.05], [0, 0, -1]],
  knee_out: ['LeftLeg', 0.02, [0.05, 0, 0], [1, 0, 0]],
  shin: ['LeftLeg', 0.5, [0, 0, 0.045], [0, 0, 1]],
  calf: ['LeftLeg', 0.4, [0, 0, -0.055], [0, 0, -1]],
  ankle: ['LeftLeg', 0.9, [0, 0, -0.03], [0, 0, -1]],
  heel: ['LeftFoot', 0.0, [0, -0.035, -0.05], [0, 0, -1]],
  foot: ['LeftFoot', 0.6, [0, 0.025, 0], [0, 1, 0]],
};

/** Midline sockets. */
const MID: Record<string, Row> = {
  crown: ['Head', 1.0, [0, 0, 0], [0, 1, 0]],
  head_back: ['Head', 0.45, [0, 0, -0.1], [0, 0, -1]],
  face: ['Head', 0.4, [0, 0, 0.1], [0, 0, 1]],
  chin: ['Head', 0.04, [0, -0.01, 0.08], [0, -0.6, 0.8]],
  neck_back: ['Neck', 0.3, [0, 0, -0.06], [0, 0, -1]],
  throat: ['Neck', 0.3, [0, 0, 0.055], [0, 0, 1]],
  chest: ['Spine2', 0.45, [0, 0, 0.12], [0, 0, 1]],
  sternum: ['Spine2', 0.1, [0, 0, 0.11], [0, 0, 1]],
  belly: ['Spine', 0.5, [0, 0, 0.1], [0, 0, 1]],
  back_upper: ['Spine2', 0.5, [0, 0, -0.12], [0, 0, -1]],
  back_mid: ['Spine1', 0.5, [0, 0, -0.12], [0, 0, -1]],
  back_lower: ['Spine', 0.3, [0, 0, -0.11], [0, 0, -1]],
  pelvis_back: ['Hips', 0.0, [0, -0.05, -0.12], [0, 0, -1]],
  groin: ['Hips', 0.0, [0, -0.12, 0.06], [0, -0.5, 0.8]],
  hips: ['Hips', 0.0, [0, 0, 0], [0, 1, 0]],
};

function mirrorBoneName(n: string): string {
  if (n.startsWith('Left')) return 'Right' + n.slice(4);
  if (n.startsWith('Right')) return 'Left' + n.slice(5);
  return n;
}

const TABLE = new Map<string, SocketDef>();
for (const [name, [bone, t, off, n]] of Object.entries(SIDED)) {
  TABLE.set(`${name}_L`, { bone: boneIndex(bone), t, off, n: norm(n) });
  TABLE.set(`${name}_R`, {
    bone: boneIndex(mirrorBoneName(bone)), t, off: [-off[0], off[1], off[2]], n: norm([-n[0], n[1], n[2]]),
  });
}
for (const [name, [bone, t, off, n]] of Object.entries(MID)) {
  // Midline chest overrides the sided chest name only for the bare id.
  TABLE.set(name, { bone: boneIndex(bone), t, off, n: norm(n) });
}

export const SOCKET_NAMES: readonly string[] = [...TABLE.keys()];

export function hasSocket(name: string): boolean {
  return TABLE.has(name);
}

export function socketDef(name: string): SocketDef {
  const d = TABLE.get(name);
  if (!d) throw new Error(`Unknown socket: ${name}`);
  return d;
}

/** Swap the side suffix of a socket name (for mirrored poses). */
export function mirrorSocket(name: string): string {
  if (name.endsWith('_L')) return name.slice(0, -2) + '_R';
  if (name.endsWith('_R')) return name.slice(0, -2) + '_L';
  return name;
}

/** Sockets on the arms and legs move when that limb is solved. */
const LIMB_BONES = new Set<number>([
  B.lArm, B.lForeArm, B.lHand, B.rArm, B.rForeArm, B.rHand,
  B.lUpLeg, B.lLeg, B.lFoot, B.rUpLeg, B.rLeg, B.rFoot,
]);
export function isLimbSocket(name: string): boolean {
  return LIMB_BONES.has(socketDef(name).bone);
}

/** Reference stature of the default rest (crown height). */
export const REF_STATURE = 1.733;

export function restScale(rest: RestSkeleton): number {
  return rest.statureM / REF_STATURE;
}

export interface SocketSample {
  p: V3;
  n: V3;
}

/** World (or pair-space) position and normal of a socket, from an FK result. */
export function sampleSocket(name: string, world: WorldPose, rest: RestSkeleton): SocketSample {
  const d = socketDef(name);
  const s = restScale(rest);
  const i = d.bone;
  const along = lerp3([0, 0, 0], [
    rest.tail[i * 3] - rest.head[i * 3],
    rest.tail[i * 3 + 1] - rest.head[i * 3 + 1],
    rest.tail[i * 3 + 2] - rest.head[i * 3 + 2],
  ], d.t);
  const local = add(along, scale(d.off, s));
  const q = getQ(world.quat, i);
  const p = add(getV3(world.pos, i), qRot(q, local));
  return { p, n: qRot(q, d.n) };
}

/** Debug: bone name for a socket. */
export function socketBoneName(name: string): string {
  return BONES[socketDef(name).bone];
}
