/**
 * Parameters owned by design chapter: docs/design/05_DAMAGE_FATIGUE_CONSCIOUSNESS.md
 * Populated from that chapter's parameter registry (§4.1 front end, §4.2 regions,
 * §4.3 consciousness, §4.4 fatigue).
 *
 * Two rows of the chapter's §4 are deliberately absent:
 *  - §4.5 `swarm.*` — the multi-opponent block. Chapter 05 §2.9 only *proposes*
 *    those numbers; chapter 07 / `multi.params.ts` owns the registry entry, and a
 *    duplicate id would throw in `ParamRegistry.add`.
 *  - the rows the design review retired: `ko.neckBrace.*` (kBrace now reads 01's
 *    `neck`), `ko.age.*` (age lives in 01 `chinEff` only — REVIEW N2), and
 *    `fat.dump.expPerFight/expMin/expMax` (01 owns `experience`).
 *
 * `free: false` marks a number fixed by a measurement: the Phase 9 calibrator
 * must not move it (registry.ts §"free"). Everything tagged `[E]` is free.
 */
import type { ParamSpec } from './registry';

interface Opts { free?: boolean; min?: number; max?: number; note?: string }

/** One registry row. `free` defaults to true: estimates are what calibration moves. */
function P(id: string, value: number, unit: string, tag: string, o: Opts = {}): ParamSpec {
  return {
    id, value, unit, tag, section: 'damage',
    free: o.free ?? true, min: o.min, max: o.max, note: o.note,
  };
}

const RATIO: Opts = { min: 0, max: 5 };
const PROB: Opts = { min: 0, max: 1 };
const POOL: Opts = { min: 0, max: 100 };

export const DAMAGE_PARAMS: ParamSpec[] = [
  // ==========================================================================
  // §4.1 Front end (dmg.*) — delivered force, absorption, raw damage
  // ==========================================================================
  // Fallback only: every §02 impact carries `placement`, so cleanMult is 1.0
  // (REVIEW: forceN is already delivered force). These three are used only by
  // ad-hoc impacts built without a placement.
  P('dmg.cleanMult.flush', 1.0, 'ratio', '[E; DAMAGE §3.1]', RATIO),
  P('dmg.cleanMult.partial', 0.5, 'ratio', '[E; DAMAGE §3.1]', RATIO),
  P('dmg.cleanMult.glancing', 0.25, 'ratio', '[E; DAMAGE §3.1]', RATIO),

  P('dmg.absorb.none', 0.0, 'ratio', '[E; DAMAGE §3.3]', PROB),
  P('dmg.absorb.block_glove', 0.5, 'ratio', '[E; DAMAGE §3.3; MT §3]', PROB),
  P('dmg.absorb.block_forearm', 0.5, 'ratio', '[E; DAMAGE §3.3; MT §3]', PROB),
  P('dmg.absorb.roll', 0.6, 'ratio', '[E; DAMAGE §3.3]', PROB),
  P('dmg.absorb.slip_late', 0.6, 'ratio', '[E; DAMAGE §3.3]', PROB),
  P('dmg.absorb.check', 0.85, 'ratio', '[E; DAMAGE §3.3; MT §3]', PROB),
  P('dmg.absorb.knee_block', 0.7, 'ratio', '[E; DAMAGE §3.3; MT §3]', PROB),
  P('dmg.absorb.catch', 0.9, 'ratio', '[E; DAMAGE §3.3]', PROB),
  P('dmg.absorb.brace', 0.3, 'ratio', '[E; DAMAGE §3.3]', PROB),
  P('dmg.absorb.gloveBlockMult.mma4oz', 0.7, 'ratio', '[E; BOX §3 D1: MMA gloves block 30-40% worse]', RATIO),
  P('dmg.absorb.gloveBlockMult.bare', 0.6, 'ratio', '[E; BOX §3 D1]', RATIO),
  P('dmg.absorb.gloveBlockMult.boxing8oz', 1.0, 'ratio', '[E; BOX §3 D1]', RATIO),
  P('dmg.absorb.gloveBlockMult.boxing10oz', 1.0, 'ratio', '[E; BOX §3 D1]', RATIO),
  P('dmg.absorb.gloveBlockMult.boxing12oz', 1.1, 'ratio', '[E; BOX §3 D1]', RATIO),
  P('dmg.absorb.rockedMult', 0.5, 'ratio', '[E; DAMAGE §3.3]', { ...RATIO, note: 'A rocked fighter absorbs half as much; the TKO path (C6, C14).' }),
  P('dmg.absorb.cap', 0.95, 'ratio', '[E]', PROB),

  P('dmg.forceRef', 3400, 'N', '[S: DAMAGE §3.1 — Walilko 2005 straight to jaw 3,427 N]', { free: false, min: 1000, max: 6000 }),
  P('dmg.rawScale', 100, '0-100', '[E]', { min: 10, max: 300, note: 'Raw damage units produced by a fully-delivered forceRef impact.' }),
  P('dmg.kWeaponDmg.fist', 1.0, 'ratio', '[E]', RATIO),
  P('dmg.kWeaponDmg.hammerfist', 0.8, 'ratio', '[E]', RATIO),
  P('dmg.kWeaponDmg.elbow', 1.1, 'ratio', '[E]', RATIO),
  P('dmg.kWeaponDmg.knee', 1.2, 'ratio', '[E]', RATIO),
  P('dmg.kWeaponDmg.shin', 1.2, 'ratio', '[E]', RATIO),
  P('dmg.kWeaponDmg.foot', 0.9, 'ratio', '[E]', RATIO),
  P('dmg.kWeaponDmg.head', 0.8, 'ratio', '[E]', RATIO),
  P('dmg.kWeaponDmg.mat', 0.6, 'ratio', '[E]', RATIO),
  P('dmg.massSev.exp', 0.5, 'ratio', '[E]', { min: 0, max: 1.5 }),
  P('dmg.massSev.min', 0.8, 'ratio', '[E]', RATIO),
  P('dmg.massSev.max', 1.3, 'ratio', '[E]', RATIO),
  P('dmg.massRef', 77, 'kg', '[D: pooled UFC male mean, FD]', { free: false, min: 50, max: 120 }),
  P('dmg.massScaleTarget.exp', -0.25, 'ratio', '[E; heavier bodies dissipate more]', { min: -1, max: 0 }),
  P('dmg.acuteAttrSlope', 0.004, 'ratio', '[E; +-20% at attr 0/100]', { min: 0, max: 0.02 }),
  P('dmg.blockToArmFraction', 0.4, 'ratio', '[S: DAMAGE §2.4 — 40% of absorbed energy into the blocking arm]', { free: false, ...PROB }),

  // ==========================================================================
  // §4.2 Regions — head
  // ==========================================================================
  P('dmg.head.acuteHalfLife', 8, 's', '[E; DAMAGE §2.1]', { min: 2, max: 30 }),
  P('dmg.head.reHit', 20, 's', '[E; DAMAGE §2.1]', { min: 5, max: 60 }),
  P('dmg.head.reHitWindow', 10, 's', '[E; DAMAGE §2.1]', { min: 1, max: 30 }),
  P('dmg.head.breakRecovery', 0.25, 'ratio', '[E; DAMAGE §2.1]', PROB),
  P('dmg.head.pFrac', 0.40, 'ratio', '[E; DAMAGE §2.1]', PROB),
  P('dmg.head.structuralRatio', 0.35, 'ratio', '[E]', RATIO),
  P('dmg.head.groundStructuralMult', 1.3, 'ratio', '[E; DAMAGE §3.2 — ground finishes accumulate]', RATIO),
  P('dmg.head.site.acute.chin', 1.35, 'ratio', '[S: DAMAGE §2.1 — 53.9% of KO blows, Hutchison 2014]', RATIO),
  P('dmg.head.site.acute.temple', 1.25, 'ratio', '[S: DAMAGE §2.1]', RATIO),
  P('dmg.head.site.acute.midface', 0.85, 'ratio', '[S: DAMAGE §2.1]', RATIO),
  P('dmg.head.site.acute.forehead', 0.60, 'ratio', '[S: DAMAGE §2.1]', RATIO),
  P('dmg.head.site.acute.orbit', 0.80, 'ratio', '[E; DAMAGE §2.1]', RATIO),
  P('dmg.head.site.acute.topback', 0.70, 'ratio', '[E; DAMAGE §2.1]', RATIO),
  P('dmg.head.site.structural.chin', 0.9, 'ratio', '[S: DAMAGE §2.1]', RATIO),
  P('dmg.head.site.structural.temple', 1.0, 'ratio', '[S: DAMAGE §2.1]', RATIO),
  P('dmg.head.site.structural.midface', 1.15, 'ratio', '[S: DAMAGE §2.1]', RATIO),
  P('dmg.head.site.structural.forehead', 0.9, 'ratio', '[S: DAMAGE §2.1]', RATIO),
  P('dmg.head.site.structural.orbit', 1.30, 'ratio', '[E; DAMAGE §2.1 — cut and swelling site]', RATIO),
  P('dmg.head.site.structural.topback', 1.0, 'ratio', '[E; DAMAGE §2.1]', RATIO),
  P('dmg.head.thr.stunned', 30, '0-100', '[E; DAMAGE §2.1]', POOL),
  P('dmg.head.thr.rocked', 45, '0-100', '[E; DAMAGE §2.1]', POOL),
  P('dmg.head.thr.kdHurt', 65, '0-100', '[E; DAMAGE §2.1]', POOL),
  P('dmg.head.thr.ko', 90, '0-100', '[E; DAMAGE §2.1]', POOL),
  P('dmg.head.exit.stunned', 25, '0-100', '[E; DAMAGE §7.6]', POOL),
  P('dmg.head.exit.rocked', 35, '0-100', '[E; DAMAGE §7.6]', POOL),
  P('dmg.head.kPriorSlope', 0.006, 'ratio', '[E; DAMAGE §2.1 — direction from Guskiewicz 2003 OR 3.0]', { min: 0, max: 0.03 }),
  P('dmg.head.kPriorCap', 1.6, 'ratio', '[E; DAMAGE §2.1]', RATIO),
  P('dmg.head.rockedSevSpan', 20, '0-100', '[D: rs = (acute - thr.rocked) / 20, saturating at thr.kdHurt]', POOL),
  P('dmg.swell.gain', 0.6, 'ratio', '[E]', RATIO),
  P('dmg.swell.breakRecovery', 0.10, 'ratio', '[E; cutman ice]', PROB),
  P('dmg.swell.visionStart', 30, '0-100', '[E]', POOL),
  P('dmg.swell.visionSpan', 50, '0-100', '[E]', POOL),
  P('dmg.swell.visionLoss', 0.6, 'ratio', '[E; vision = 1 - 0.6 x ramp]', PROB),
  P('dmg.swell.shutAt', 70, '0-100', '[S: DAMAGE §5.2 — 06 eyeSwollenShut]', { free: false, ...POOL }),
  P('dmg.swell.shutVision', 0.2, 'ratio', '[E; floor vision through a closed eye]', PROB),
  P('dmg.nose.breakP', 0.02, 'probability', '[E; Bledsoe 2006 nose 10.4% of MMA injuries; Jones 2023 3.6% facial fracture]', PROB),
  P('dmg.nose.rawMin', 30, '0-100', '[E]', POOL),
  P('dmg.nose.aerobicMult', 0.92, 'ratio', '[E; mouth breathing]', RATIO),
  P('dmg.nose.doctorStructural', 80, '0-100', '[S: DAMAGE §5.2]', { free: false, ...POOL }),

  // ---- body ----------------------------------------------------------------
  P('dmg.body.acuteHalfLife', 12, 's', '[E; DAMAGE §2.2]', { min: 2, max: 40 }),
  P('dmg.body.reHit', 20, 's', '[E; DAMAGE §2.2]', { min: 5, max: 60 }),
  P('dmg.body.reHitWindow', 10, 's', '[E; DAMAGE §2.2]', { min: 1, max: 30 }),
  P('dmg.body.breakRecovery', 0.15, 'ratio', '[E; DAMAGE §2.2]', PROB),
  P('dmg.body.pFrac', 0.30, 'ratio', '[E; DAMAGE §2.2]', PROB),
  P('dmg.body.structuralRatio', 0.40, 'ratio', '[E; MT §5.1 — clean T2 shin body kick = 8-14 structural]', RATIO),
  P('dmg.body.site.acute.liver', 1.3, 'ratio', '[E; DAMAGE §2.2, MT §5.3]', RATIO),
  P('dmg.body.site.acute.solar', 1.2, 'ratio', '[E; DAMAGE §2.2]', RATIO),
  P('dmg.body.site.acute.ribs', 1.0, 'ratio', '[E; MT §5.3]', RATIO),
  P('dmg.body.site.acute.spleen', 1.1, 'ratio', '[E; DAMAGE §2.2]', RATIO),
  P('dmg.body.site.acute.sternum', 0.8, 'ratio', '[E; DAMAGE §2.2]', RATIO),
  P('dmg.body.site.acute.abdomen', 0.9, 'ratio', '[E; DAMAGE §2.2]', RATIO),
  P('dmg.body.site.structural.liver', 1.0, 'ratio', '[E; DAMAGE §2.2]', RATIO),
  P('dmg.body.site.structural.solar', 0.8, 'ratio', '[E; DAMAGE §2.2]', RATIO),
  P('dmg.body.site.structural.ribs', 1.2, 'ratio', '[E; MT §5.3]', RATIO),
  P('dmg.body.site.structural.spleen', 1.0, 'ratio', '[E; DAMAGE §2.2]', RATIO),
  P('dmg.body.site.structural.sternum', 0.9, 'ratio', '[E; DAMAGE §2.2]', RATIO),
  P('dmg.body.site.structural.abdomen', 0.8, 'ratio', '[E; DAMAGE §2.2]', RATIO),
  P('dmg.body.thr.hurt', 50, '0-100', '[E; DAMAGE §2.2]', POOL),
  P('dmg.body.thr.hurtExit', 35, '0-100', '[E; DAMAGE §2.2]', POOL),
  P('dmg.body.thr.worn', 40, '0-100', '[E; MT §5.3]', POOL),
  P('dmg.body.thr.worn2', 60, '0-100', '[E; MT §5.3]', POOL),
  P('dmg.body.thr.wornExit', 35, '0-100', '[E; DAMAGE §2.2]', POOL),
  P('dmg.body.thr.collapse', 80, '0-100', '[E; DAMAGE §2.2]', POOL),
  P('dmg.body.thr.collapseRollAt', 80, '0-100', '[S: MT §5.3]', POOL),
  P('dmg.body.collapseRollP', 0.25, 'probability', '[S: MT §5.3]', { free: false, ...PROB }),
  P('dmg.body.liver.rawThr', 35, '0-100', '[E; DAMAGE §2.2]', POOL),
  P('dmg.body.liver.delayMin', 0.5, 's', '[E; DAMAGE §2.2 — the delayed collapse]', { min: 0, max: 10 }),
  P('dmg.body.liver.delayMax', 3.0, 's', '[E; DAMAGE §2.2]', { min: 0, max: 10 }),
  P('dmg.body.liver.downMin', 5, 's', '[E; DAMAGE §2.2]', { min: 0, max: 60 }),
  P('dmg.body.liver.downMax', 20, 's', '[E; DAMAGE §2.2]', { min: 0, max: 60 }),
  P('dmg.body.solar.rawThr', 30, '0-100', '[E; DAMAGE §2.2]', POOL),
  P('dmg.body.solar.windedMin', 3, 's', '[E; DAMAGE §2.2]', { min: 0, max: 60 }),
  P('dmg.body.solar.windedMax', 15, 's', '[E; DAMAGE §2.2]', { min: 0, max: 60 }),
  P('dmg.body.ribFractureP', 0.01, 'probability', '[S: MT §5.3 — rib trauma ~1% of athlete-injuries]', { free: false, ...PROB }),
  P('dmg.body.tier4Raw', 45, '0-100', '[S: MT §5.3 — "clean tier-4 kick/knee"]', POOL),
  P('dmg.body.toughnessThrSlope', 0.005, 'ratio', '[E; DAMAGE §7.22 painTolerance +-25%]', { min: 0, max: 0.02 }),

  // ---- legs ----------------------------------------------------------------
  P('dmg.leg.acuteHalfLife', 20, 's', '[E; DAMAGE §2.3]', { min: 5, max: 60 }),
  P('dmg.leg.reHit', 30, 's', '[E; DAMAGE §2.3]', { min: 5, max: 90 }),
  P('dmg.leg.reHitWindow', 15, 's', '[E; DAMAGE §2.3]', { min: 1, max: 40 }),
  P('dmg.leg.breakRecovery', 0.10, 'ratio', '[E; MT §5.1 "1-2 points per minute of rest"]', PROB),
  P('dmg.leg.pFrac', 0.50, 'ratio', '[E; DAMAGE §2.3]', PROB),
  P('dmg.leg.structuralRatio', 0.40, 'ratio', '[D: 0.40 x raw 25 = 10 thigh for a clean T2 low kick, MT §5.1]', RATIO),
  P('dmg.leg.site.acute.thigh', 1.0, 'ratio', '[E; DAMAGE §2.3]', RATIO),
  P('dmg.leg.site.acute.calf', 0.8, 'ratio', '[E; DAMAGE §2.3]', RATIO),
  P('dmg.leg.site.acute.shin', 0.5, 'ratio', '[E; DAMAGE §2.3]', RATIO),
  P('dmg.leg.site.acute.knee', 0.6, 'ratio', '[E; MT §8.9]', RATIO),
  P('dmg.leg.site.structural.thigh', 1.0, 'ratio', '[S: MT §5.1]', RATIO),
  P('dmg.leg.site.structural.calf', 1.5, 'ratio', '[S: DAMAGE §2.3 — calf kicks bite harder per point]', RATIO),
  P('dmg.leg.site.structural.shin', 1.0, 'ratio', '[S: MT §5.2]', RATIO),
  P('dmg.leg.site.structural.knee', 1.0, 'ratio', '[E; MT §8.9]', RATIO),
  P('dmg.leg.loadWeight.calf', 1.1, 'ratio', '[E]', RATIO),
  P('dmg.leg.loadWeight.knee', 1.2, 'ratio', '[E]', RATIO),
  P('dmg.leg.mobility.a', 0.7, 'ratio', '[S: DAMAGE §2.3]', { free: false, ...RATIO }),
  P('dmg.leg.mobility.p', 1.5, 'ratio', '[S: DAMAGE §2.3]', { free: false, min: 0.5, max: 3 }),
  P('dmg.leg.kickPower.a', 0.5, 'ratio', '[E; MT §5.1 bands 0.9/0.75/0.5]', RATIO),
  P('dmg.leg.kickPower.p', 1.2, 'ratio', '[E; MT §5.1]', { min: 0.5, max: 3 }),
  P('dmg.leg.checkSpeed.a', 0.5, 'ratio', '[E; MT §5.1]', RATIO),
  P('dmg.leg.checkSpeed.p', 1.3, 'ratio', '[E; MT §5.1]', { min: 0.5, max: 3 }),
  P('dmg.leg.tdd.a', 0.45, 'ratio', '[E; MT §5.1 bands 0.92/0.80/0.60]', RATIO),
  P('dmg.leg.tdd.p', 1.2, 'ratio', '[E; MT §5.1]', { min: 0.5, max: 3 }),
  P('dmg.leg.worseLegWeight', 0.7, 'ratio', '[S: DAMAGE §2.3 — "worse leg at 70% weight"]', { free: false, ...PROB }),
  P('dmg.leg.rearHandPower.drop', 0.2, 'ratio', '[S: DAMAGE §2.3 — load 55 costs the rear hand 20%]', PROB),
  P('dmg.leg.rearHandPower.start', 40, '0-100', '[E; smoothing of DAMAGE §2.3s hard threshold]', POOL),
  P('dmg.leg.rearHandPower.span', 30, '0-100', '[E]', POOL),
  P('dmg.leg.thr.sev1', 30, '0-100', '[E; DAMAGE §2.3]', POOL),
  P('dmg.leg.thr.sev2', 55, '0-100', '[E; DAMAGE §2.3]', POOL),
  P('dmg.leg.thr.sev3', 75, '0-100', '[E; DAMAGE §2.3]', POOL),
  P('dmg.leg.thr.collapse', 85, '0-100', '[E; DAMAGE §2.3]', POOL),
  P('dmg.leg.thr.collapseAcute', 70, '0-100', '[E; DAMAGE §2.3]', POOL),
  P('dmg.leg.thr.cannotStandAcute', 50, '0-100', '[E; §2.6.2 — cannotStand until leg acute < 50]', POOL),
  P('dmg.leg.collapseFallP', 0.30, 'probability', '[S: MT §8.22]', { free: false, ...PROB }),
  P('dmg.leg.calfShock.base', 0.08, 'probability', '[S: MT §5.1]', PROB),
  P('dmg.leg.calfShock.perHit', 0.02, 'probability', '[S: MT §5.1 — rising form reproduces "5-10 clean calf kicks"]', PROB),
  P('dmg.leg.calfShock.cap', 0.18, 'probability', '[S: MT §5.1]', PROB),
  P('dmg.leg.calfShock.durMin', 15, 's', '[E; MT 15 s, DAMAGE 30-90 s — MT window used]', { min: 1, max: 120 }),
  P('dmg.leg.calfShock.durMax', 30, 's', '[E]', { min: 1, max: 120 }),
  P('dmg.leg.deadLeg.move', 0.7, 'ratio', '[E; MT §5.1]', RATIO),
  P('dmg.leg.deadLeg.check', 0.5, 'ratio', '[E; MT §5.1]', RATIO),
  P('dmg.leg.deadLeg.kick', 0.6, 'ratio', '[E; MT §5.1]', RATIO),
  P('dmg.leg.deadLeg.tdd', 0.75, 'ratio', '[E; MT §5.1]', RATIO),
  P('dmg.leg.kneeEventP', 0.05, 'probability', '[S: MT §8.9 — oblique kick]', { free: false, ...PROB }),
  P('dmg.leg.kneeMove', 0.8, 'ratio', '[S: MT §8.9]', RATIO),
  P('dmg.leg.kneeTdEntry', -0.15, 'logit', '[S: MT §8.9]', { min: -1, max: 0 }),
  P('dmg.leg.checkReturnForce', 0.6, 'ratio', '[S: DAMAGE §2.3 — the kicker eats 60% of his own force]', { free: false, ...RATIO }),
  P('dmg.leg.checkDefenderAbsorb', 0.85, 'ratio', '[S: MT §3 — the checker takes 0-20%]', { free: false, ...PROB }),
  P('dmg.leg.shinFractureP', 0.002, 'probability', '[S: MT §5.2 — two in ~30 years of UFC title fights]', { free: false, ...PROB }),
  P('dmg.leg.shinFractureForceMin', 1800, 'N', '[E; T3+ intensity gate]', { min: 500, max: 5000 }),
  P('dmg.leg.shin.band1', 26, '0-100', '[S: MT §5.2]', POOL),
  P('dmg.leg.shin.band2', 51, '0-100', '[S: MT §5.2]', POOL),
  P('dmg.leg.shin.band3', 76, '0-100', '[S: MT §5.2]', POOL),
  P('dmg.leg.shin.freq1', 0.8, 'ratio', '[S: MT §5.2]', RATIO),
  P('dmg.leg.shin.pow1', 0.9, 'ratio', '[S: MT §5.2]', RATIO),
  P('dmg.leg.shin.freq2', 0.6, 'ratio', '[S: MT §5.2]', RATIO),
  P('dmg.leg.shin.pow2', 0.8, 'ratio', '[S: MT §5.2]', RATIO),

  // ---- arms, hands, feet ---------------------------------------------------
  P('dmg.arm.acuteHalfLife', 15, 's', '[E]', { min: 2, max: 60 }),
  P('dmg.arm.reHit', 25, 's', '[E]', { min: 5, max: 90 }),
  P('dmg.arm.reHitWindow', 10, 's', '[E]', { min: 1, max: 30 }),
  P('dmg.arm.breakRecovery', 0.20, 'ratio', '[E]', PROB),
  P('dmg.arm.pFrac', 0.30, 'ratio', '[E]', PROB),
  P('dmg.arm.directAcute', 0.6, 'ratio', '[E; kick into the guard]', RATIO),
  P('dmg.arm.directStructural', 0.35, 'ratio', '[E]', RATIO),
  P('dmg.arm.deadArmThr', 50, '0-100', '[S: DAMAGE §2.4]', { free: false, ...POOL }),
  P('dmg.arm.deadArmExit', 40, '0-100', '[E]', POOL),
  P('dmg.arm.deadArmMinDur', 60, 's', '[E]', { min: 0, max: 600 }),
  P('dmg.arm.deadArmGuard', 0.75, 'ratio', '[S: DAMAGE §2.4]', RATIO),
  P('dmg.arm.deadArmPower', 0.8, 'ratio', '[S: DAMAGE §2.4]', RATIO),
  P('dmg.hand.pSkull', 0.0015, 'probability', '[E; DAMAGE §2.4 — forehead/topback/temple]', PROB),
  P('dmg.hand.pSoft', 0.0004, 'probability', '[E; DAMAGE §2.4 — chin/midface/orbit/body]', PROB),
  P('dmg.hand.pHammerElbow', 0.0002, 'probability', '[E; DAMAGE §2.4]', PROB),
  P('dmg.hand.gloveMult.mma4oz', 1.0, 'ratio', '[E]', RATIO),
  P('dmg.hand.gloveMult.bare', 2.5, 'ratio', '[E]', RATIO),
  P('dmg.hand.gloveMult.boxing', 0.6, 'ratio', '[E]', RATIO),
  P('dmg.hand.power', 0.65, 'ratio', '[S: DAMAGE §2.4]', RATIO),
  P('dmg.hand.useFreq', 0.5, 'ratio', '[S: DAMAGE §2.4 — 07 hook handUseFrequency]', RATIO),
  P('dmg.foot.p', 0.003, 'probability', '[S: DAMAGE §2.4 — kick onto an elbow or knee]', { free: false, ...PROB }),
  P('dmg.foot.power', 0.6, 'ratio', '[E]', RATIO),
  P('dmg.foot.freq', 0.4, 'ratio', '[E]', RATIO),

  // ---- cuts ----------------------------------------------------------------
  P('dmg.cut.p.elbowHoriz.brow', 0.12, 'probability', '[S: MT §5.4]', { free: false, ...PROB }),
  P('dmg.cut.p.elbowHoriz.other', 0.06, 'probability', '[E; DAMAGE §2.5]', PROB),
  P('dmg.cut.p.elbowDown.brow', 0.18, 'probability', '[S: MT §5.4 — 12-6 legal in MMA-unified since Nov 2024]', { free: false, ...PROB }),
  P('dmg.cut.p.elbowDown.other', 0.08, 'probability', '[S: MT §5.4]', PROB),
  P('dmg.cut.p.elbowUp.brow', 0.08, 'probability', '[S: MT §5.4]', { free: false, ...PROB }),
  P('dmg.cut.p.elbowUp.other', 0.04, 'probability', '[S: MT §5.4]', PROB),
  P('dmg.cut.p.fistMma.brow', 0.012, 'probability', '[E; DAMAGE §2.5]', PROB),
  P('dmg.cut.p.fistMma.other', 0.004, 'probability', '[E; DAMAGE §2.5]', PROB),
  P('dmg.cut.p.fistBoxing.brow', 0.008, 'probability', '[E; LIT_A §4 Bledsoe 2005 ~1.7% per boxer-round]', PROB),
  P('dmg.cut.p.fistBoxing.other', 0.003, 'probability', '[E; LIT_A §4]', PROB),
  P('dmg.cut.p.fistBare.brow', 0.025, 'probability', '[E]', PROB),
  P('dmg.cut.p.fistBare.other', 0.008, 'probability', '[E]', PROB),
  P('dmg.cut.p.knee.brow', 0.03, 'probability', '[E; DAMAGE §2.5]', PROB),
  P('dmg.cut.p.knee.other', 0.015, 'probability', '[E; DAMAGE §2.5]', PROB),
  P('dmg.cut.p.headClash.brow', 0.08, 'probability', '[E; DAMAGE §2.5]', PROB),
  P('dmg.cut.p.headClash.other', 0.04, 'probability', '[E; DAMAGE §2.5]', PROB),
  P('dmg.cut.p.shinFoot.brow', 0.02, 'probability', '[E]', PROB),
  P('dmg.cut.p.shinFoot.other', 0.01, 'probability', '[E]', PROB),
  P('dmg.cut.pronenessPerCareerCut', 0.01, 'ratio', '[E]', { min: 0, max: 0.1 }),
  P('dmg.cut.pronenessCap', 1.5, 'ratio', '[E]', RATIO),
  P('dmg.cut.structuralSlope', 0.005, 'ratio', '[E; swollen tissue splits more easily]', { min: 0, max: 0.05 }),
  P('dmg.cut.sevWeight1', 0.60, 'ratio', '[S: DAMAGE §2.5]', PROB),
  P('dmg.cut.sevWeight2', 0.30, 'ratio', '[S: DAMAGE §2.5]', PROB),
  P('dmg.cut.sevWeight3', 0.10, 'ratio', '[S: DAMAGE §2.5]', PROB),
  P('dmg.cut.sevWeightElbow1', 0.45, 'ratio', '[E]', PROB),
  P('dmg.cut.sevWeightElbow2', 0.35, 'ratio', '[E]', PROB),
  P('dmg.cut.sevWeightElbow3', 0.20, 'ratio', '[E]', PROB),
  P('dmg.cut.growthHits', 5, 'count', '[S: DAMAGE §2.5 — +1 severity per 5 further clean strikes]', { free: false, min: 1, max: 20 }),
  P('dmg.cut.vision.sev2', 0.75, 'ratio', '[S: DAMAGE §2.5]', RATIO),
  P('dmg.cut.vision.sev3', 0.5, 'ratio', '[S: DAMAGE §2.5]', RATIO),
  P('dmg.cut.visionFloor', 0.2, 'ratio', '[S: DAMAGE §2.5 — compounds with swelling, floor 0.2]', PROB),
  P('dmg.cut.bloodRecentS', 120, 's', '[E]', { min: 0, max: 600 }),
  P('dmg.cut.cutmanReduce', 1, 'count', '[S: DAMAGE §2.5]', { free: false, min: 0, max: 3 }),
  P('dmg.cut.reopenHits', 2, 'count', '[S: DAMAGE §2.5]', { free: false, min: 1, max: 10 }),
  P('dmg.cut.doctor.bloodInEyeS', 60, 's', '[S: DAMAGE §5.2]', { free: false, min: 0, max: 600 }),
  P('dmg.vision.defence.floor', 0.6, 'ratio', '[S: DAMAGE §2.5 — -10/-25/-50% bands]', RATIO),
  P('dmg.vision.accuracy.floor', 0.7, 'ratio', '[S: DAMAGE §2.5]', RATIO),
  P('dmg.recoveryAttrSlope', 0.003, 'ratio', '[E; +-15% at recovery 0/100 — halved from DAMAGE §7.22 because §2.6 also gives recovery the rocked-exit speed]', { min: 0, max: 0.02 }),

  // ---- §2.3.7 capability-multiplier table ----------------------------------
  // The chapter's §4 registry does not list these cells, but §6.1 item 10 names
  // the whole table as an estimate that calibration must be able to move, so
  // every cell is registered. Rows whose effect is a curve (legs) or lives in
  // another block (dead arm, hand/foot injury, vision) are not repeated here.
  P('dmg.caps.stunned.defence', 0.90, 'ratio', '[E; DAMAGE §2.1]', RATIO),
  P('dmg.caps.stunned.accuracy', 0.90, 'ratio', '[E; DAMAGE §2.1]', RATIO),
  P('dmg.caps.stunned.decision', 0.95, 'ratio', '[E; DAMAGE §2.1]', RATIO),
  P('dmg.caps.stunned.tdd', 0.95, 'ratio', '[E; DAMAGE §2.1]', RATIO),
  P('dmg.caps.stunned.reactionLatency', 1.15, 'ratio', '[E; DAMAGE §2.1 — reaction latency +15%]', RATIO),
  P('dmg.caps.rocked.movement', 0.6, 'ratio', '[S: DAMAGE §2.1 values at rs = 0]', RATIO),
  P('dmg.caps.rocked.movementSev', 0.1, 'ratio', '[E; linear in rs]', RATIO),
  P('dmg.caps.rocked.defence', 0.65, 'ratio', '[S: DAMAGE §2.1]', RATIO),
  P('dmg.caps.rocked.defenceSev', 0.15, 'ratio', '[E; linear in rs]', RATIO),
  P('dmg.caps.rocked.accuracy', 0.75, 'ratio', '[S: DAMAGE §2.1]', RATIO),
  P('dmg.caps.rocked.power', 0.85, 'ratio', '[S: DAMAGE §2.1]', RATIO),
  P('dmg.caps.rocked.speed', 0.9, 'ratio', '[S: DAMAGE §2.1]', RATIO),
  P('dmg.caps.rocked.decision', 0.6, 'ratio', '[S: DAMAGE §2.1 — "fights on instinct"]', RATIO),
  P('dmg.caps.rocked.decisionSev', 0.2, 'ratio', '[E; linear in rs]', RATIO),
  P('dmg.caps.rocked.tdd', 0.70, 'ratio', '[E; DAMAGE §2.1]', RATIO),
  P('dmg.caps.rocked.output', 0.9, 'ratio', '[E; DAMAGE §2.1]', RATIO),
  P('dmg.caps.kdHurt.defence', 0.5, 'ratio', '[E; DAMAGE §2.1]', RATIO),
  P('dmg.caps.kdHurt.accuracy', 0.7, 'ratio', '[E; DAMAGE §2.1]', RATIO),
  P('dmg.caps.kdHurt.power', 0.8, 'ratio', '[E; DAMAGE §2.1]', RATIO),
  P('dmg.caps.kdHurt.speed', 0.85, 'ratio', '[E; DAMAGE §2.1]', RATIO),
  P('dmg.caps.kdHurt.decision', 0.4, 'ratio', '[E; DAMAGE §2.1 — survival mode]', RATIO),
  P('dmg.caps.kdHurt.tdd', 0.5, 'ratio', '[E; DAMAGE §2.1]', RATIO),
  P('dmg.caps.kdHurt.output', 0.7, 'ratio', '[E; DAMAGE §2.1]', RATIO),
  P('dmg.caps.bodyHurt.movement', 0.8, 'ratio', '[E; DAMAGE §2.2]', RATIO),
  P('dmg.caps.bodyHurt.defence', 0.75, 'ratio', '[E; DAMAGE §2.2 — head exposure +30% as the guard drops]', RATIO),
  P('dmg.caps.bodyHurt.accuracy', 0.9, 'ratio', '[E; DAMAGE §2.2]', RATIO),
  P('dmg.caps.bodyHurt.power', 0.9, 'ratio', '[E; DAMAGE §2.2]', RATIO),
  P('dmg.caps.bodyHurt.decision', 0.9, 'ratio', '[E; DAMAGE §2.2]', RATIO),
  P('dmg.caps.bodyHurt.tdd', 0.9, 'ratio', '[E; DAMAGE §2.2]', RATIO),
  P('dmg.caps.bodyHurt.output', 0.7, 'ratio', '[E; DAMAGE §2.2]', RATIO),
  P('dmg.caps.winded.movement', 0.6, 'ratio', '[E]', RATIO),
  P('dmg.caps.winded.defence', 0.7, 'ratio', '[E]', RATIO),
  P('dmg.caps.winded.accuracy', 0.8, 'ratio', '[E]', RATIO),
  P('dmg.caps.winded.power', 0.7, 'ratio', '[E]', RATIO),
  P('dmg.caps.winded.speed', 0.9, 'ratio', '[E]', RATIO),
  P('dmg.caps.winded.decision', 0.8, 'ratio', '[E]', RATIO),
  P('dmg.caps.winded.tdd', 0.6, 'ratio', '[E]', RATIO),
  P('dmg.caps.winded.output', 0.3, 'ratio', '[E; cannot breathe]', RATIO),
  P('dmg.caps.bodyCollapse.defence', 0.3, 'ratio', '[E; cannot intelligently defend]', RATIO),
  P('dmg.caps.bodyCollapse.decision', 0.3, 'ratio', '[E]', RATIO),
  P('dmg.caps.legCompromised.kickRate1', 0.8, 'ratio', '[E; kicks from the damaged leg, sev 1]', RATIO),
  P('dmg.caps.legCompromised.kickRate2', 0.6, 'ratio', '[E; sev 2]', RATIO),
  P('dmg.caps.legCompromised.kickRate3', 0.4, 'ratio', '[E; sev 3]', RATIO),
  P('dmg.caps.jointFailure.tdd', 0.5, 'ratio', '[E; §2.3.8 — a failed knee halves TDD]', RATIO),
  P('dmg.caps.neckCranked.braceMult', 1.1, 'ratio', '[E; §2.3.8 — residual neck strain raises kBrace]', RATIO),

  // ==========================================================================
  // §4.3 Consciousness (ko.*, kd.*, rec.*)
  // ==========================================================================
  P('ko.alphaRef', 6300, 'rad/s^2', '[S: DAMAGE §3.1 — Walilko 2005: 3,427 N -> 6,343 rad/s^2]', { free: false, min: 3000, max: 12000 }),
  P('ko.forceRef', 3400, 'N', '[S: DAMAGE §3.1]', { free: false, min: 1000, max: 6000 }),
  P('ko.kWeapon.straight', 1.0, 'ratio', '[S: DAMAGE §3.1]', RATIO),
  P('ko.kWeapon.uppercut', 1.05, 'ratio', '[E]', RATIO),
  P('ko.kWeapon.hook', 1.15, 'ratio', '[D: (9,306/6,343)/(4,405/3,427) = 1.14 — Viano 2005 vs Walilko 2005]', RATIO),
  P('ko.kWeapon.elbow', 1.15, 'ratio', '[S: DAMAGE §3.1 "elbows ~ hooks"]', RATIO),
  P('ko.kWeapon.knee', 1.2, 'ratio', '[E; DAMAGE §3.1 1.5x a hook in alphaEq, but knee force is already 1.4x from 02]', RATIO),
  P('ko.kWeapon.shin', 1.2, 'ratio', '[E; DAMAGE §3.1 1.5-2x hook; Fife 2013 is the only datum]', RATIO),
  P('ko.kWeapon.foot', 1.1, 'ratio', '[E]', RATIO),
  P('ko.kWeapon.hammerfist', 0.6, 'ratio', '[S: DAMAGE §3.1]', RATIO),
  P('ko.kWeapon.mat', 0.35, 'ratio', '[E; Lota 2022 judo throws 276-5,081 rad/s^2, mostly sub-threshold]', RATIO),
  P('ko.kWeapon.head', 0.8, 'ratio', '[E; clash]', RATIO),
  P('ko.kLever.chin', 1.3, 'ratio', '[S: DAMAGE §3.1]', RATIO),
  P('ko.kLever.temple', 1.2, 'ratio', '[S: DAMAGE §3.1]', RATIO),
  P('ko.kLever.midface', 0.8, 'ratio', '[S: DAMAGE §3.1]', RATIO),
  P('ko.kLever.forehead', 0.7, 'ratio', '[S: DAMAGE §3.1]', RATIO),
  P('ko.kLever.orbit', 0.8, 'ratio', '[E; DAMAGE §3.1]', RATIO),
  P('ko.kLever.topback', 0.7, 'ratio', '[E; DAMAGE §3.1]', RATIO),
  P('ko.kGlove.mma4oz', 1.15, 'ratio', '[E; LIT_A §2 Bartsch 2012 — padding cuts linear, not rotational]', RATIO),
  P('ko.kGlove.bare', 1.20, 'ratio', '[E; LIT_A §2]', RATIO),
  P('ko.kGlove.boxing8oz', 1.00, 'ratio', '[E; LIT_A §2]', RATIO),
  P('ko.kGlove.boxing10oz', 0.97, 'ratio', '[E; LIT_A §2]', RATIO),
  P('ko.kGlove.boxing12oz', 0.93, 'ratio', '[E; LIT_A §2]', RATIO),
  P('ko.kUnseen', 1.35, 'ratio', '[S: DAMAGE §3.2 — Eckner 2014, Mihalik 2010; magnitude E]', RATIO),
  P('ko.kBrace.a', 1.15, 'ratio', '[S: DAMAGE §3.2 form — Collins 2014, -5% odds per lb neck strength; = 01 fm.attr.neck_mult_a]', RATIO),
  P('ko.kBrace.b', 0.30, 'ratio', '[S: DAMAGE §3.2 form; = 01 fm.attr.neck_mult_b]', RATIO),
  P('ko.kRelaxed', 1.2, 'ratio', '[E; DAMAGE §3.2 — caught mid-action or mouth open]', RATIO),
  P('ko.kClosing.max', 0.5, 'ratio', '[E; DAMAGE §3.2]', RATIO),
  P('ko.kClosing.speedRef', 3, 'm/s', '[E; DAMAGE §3.2]', { min: 0.5, max: 10 }),
  P('ko.kFatigue', 0.25, 'ratio', '[E; DAMAGE §3.2 — C4 says keep <= 0.25]', { min: 0, max: 0.5 }),
  P('ko.kGround', 0.7, 'ratio', '[E; DAMAGE §3.2 — the mat backs the head up]', RATIO),
  P('ko.alphaCal', 1.0, 'ratio', '[E]', { min: 0.5, max: 2, note: 'Single calibration knob for C1-C3; expect ~0.9 once 02 lands.' }),
  P('ko.alpha50', 8500, 'rad/s^2', '[D: Rowson & Duma 2013 combined logistic collapsed onto the punch a:alpha ratio — §2.4.1]', { min: 5000, max: 12000 }),
  P('ko.alphaScale', 1000, 'rad/s^2', '[D: reproduces CP(6,343)=0.07, CP(9,306)=0.66 within +-0.03 — §2.4.1]', { min: 300, max: 3000 }),
  P('ko.chinSlope', 0.02, 'logit', '[E; DAMAGE §3.2 — "a 0.9 chin needs ~+1,450 rad/s^2 more"]', { min: 0, max: 0.1 }),
  P('ko.dehydSlope', 3, 'logit', '[E; DAMAGE §3.2, §4.7 — per unit residual-dehydration fraction]', { min: 0, max: 20 }),
  P('ko.kKO', 0.20, 'ratio', '[E; DAMAGE §3.2 gives 0.22 as "the least-supported constant in the model"]', PROB),
  P('ko.kKO.fatigue', 0.4, 'ratio', '[E; tired fighters drop and stay down]', { min: 0, max: 2 }),
  P('ko.split.hurtKD', 0.10, 'ratio', '[E; DAMAGE §3.2 — split rocked 45 / flash 25 / hurt 8-10 / KO 20-22]', PROB),
  P('ko.split.flashKD', 0.25, 'ratio', '[E; DAMAGE §3.2]', PROB),
  P('ko.massSevKO.exp', 0.8, 'ratio', '[E; the weight-class gradient lives in severity, not frequency]', { min: 0, max: 2 }),
  P('ko.massSevKO.min', 0.6, 'ratio', '[E]', RATIO),
  P('ko.massSevKO.max', 1.5, 'ratio', '[E]', RATIO),
  P('ko.historyPerKO', 0.25, 'ratio', '[S: DAMAGE §3.2 form — Hutchison, Guskiewicz; slope E. = 01 fm.career.kko_history_per_ko]', { min: 0, max: 1 }),
  P('ko.historyCap', 4, 'count', '[E; = 01 cap on koLosses counted]', { min: 0, max: 20 }),
  P('ko.careerChinLoss', 3, '0-100', '[E; DAMAGE §7.21 — 0.03 on a 0-1 scale, per KO/TKO loss]', { min: 0, max: 20 }),
  P('ko.unconsciousMin', 5, 's', '[E; DAMAGE §2.1]', { min: 0, max: 300 }),
  P('ko.unconsciousMax', 90, 's', '[E; DAMAGE §2.1 — must exceed 06s referee lag, C15]', { min: 0, max: 300 }),
  P('kd.hurt.acuteFloor', 70, '0-100', '[E; DAMAGE §2.1]', POOL),
  P('kd.hurt.freezeMin', 10, 's', '[E; a hurt fighters legs come back slowly]', { min: 0, max: 120 }),
  P('kd.hurt.freezeMax', 25, 's', '[E; DAMAGE §2.1 — "15-40 s after a hurt knockdown"]', { min: 0, max: 120 }),
  P('kd.hurt.riseMin', 1, 's', '[E; DAMAGE §2.1]', { min: 0, max: 30 }),
  P('kd.hurt.riseMax', 3, 's', '[E; DAMAGE §2.1]', { min: 0, max: 30 }),
  P('kd.flash.acuteFloor', 55, '0-100', '[E; DAMAGE §2.1]', POOL),
  P('kd.flash.groundedMin', 1, 's', '[E; DAMAGE §2.1]', { min: 0, max: 30 }),
  P('kd.flash.groundedMax', 3, 's', '[E; DAMAGE §2.1]', { min: 0, max: 30 }),
  P('kd.rocked.acuteFloor', 50, '0-100', '[E]', POOL),
  P('kd.survivalTax.pcr', 4, '0-100', '[E; DAMAGE §4.2 — adrenaline, flailing]', { min: 0, max: 50 }),
  P('kd.survivalTax.lac', 0.4, 'mmol/L', '[E; DAMAGE §4.2]', { min: 0, max: 5 }),
  P('rec.rockedHalfLife', 8, 's', '[S: DAMAGE §3.4]', { free: false, min: 1, max: 40 }),
  P('rec.fatigueSlope', 0.6, 'ratio', '[D: 8 s -> 13 s at f = 0.8]', { min: 0, max: 3 }),

  // ==========================================================================
  // §4.4 Fatigue (fat.*)
  // ==========================================================================
  P('fat.cardioSlope', 0.008, 'ratio', '[E; +-40% at cardio 0/100]', { min: 0, max: 0.03 }),
  // per-action costs, §2.5.1. `.pcr` in pool units, `.lac` in mmol/L.
  P('fat.cost.lightStrike.pcr', 0.8, '0-100', '[E; DAMAGE §4.2]', { min: 0, max: 50 }),
  P('fat.cost.lightStrike.lac', 0.05, 'mmol/L', '[E; DAMAGE §4.2]', { min: 0, max: 5 }),
  P('fat.cost.feint.pcr', 0.4, '0-100', '[E; DAMAGE §4.2]', { min: 0, max: 50 }),
  P('fat.cost.feint.lac', 0.02, 'mmol/L', '[E; DAMAGE §4.2]', { min: 0, max: 5 }),
  P('fat.cost.powerStrike.pcr', 2.5, '0-100', '[E; DAMAGE §4.2 — one 5-min round of average activity ~ 100 PCr-units]', { min: 0, max: 50 }),
  P('fat.cost.powerStrike.lac', 0.15, 'mmol/L', '[E; DAMAGE §4.2]', { min: 0, max: 5 }),
  P('fat.cost.heavyStrike.pcr', 3.5, '0-100', '[E; DAMAGE §4.2]', { min: 0, max: 50 }),
  P('fat.cost.heavyStrike.lac', 0.20, 'mmol/L', '[E; DAMAGE §4.2]', { min: 0, max: 5 }),
  P('fat.cost.takedownAttempt.pcr', 10, '0-100', '[E; DAMAGE §4.2 — failed costs the same]', { min: 0, max: 50 }),
  P('fat.cost.takedownAttempt.lac', 0.8, 'mmol/L', '[E; DAMAGE §4.2]', { min: 0, max: 5 }),
  P('fat.cost.sprawl.pcr', 6, '0-100', '[E; DAMAGE §4.2]', { min: 0, max: 50 }),
  P('fat.cost.sprawl.lac', 0.5, 'mmol/L', '[E; DAMAGE §4.2]', { min: 0, max: 5 }),
  P('fat.cost.clinchPummel.pcr', 5, '0-100', '[E; DAMAGE §4.2 — per 10 s, isometric]', { min: 0, max: 50 }),
  P('fat.cost.clinchPummel.lac', 0.6, 'mmol/L', '[E; DAMAGE §4.2]', { min: 0, max: 5 }),
  P('fat.cost.clinchHoldDominant.pcr', 3, '0-100', '[E; cheaper than pummelling]', { min: 0, max: 50 }),
  P('fat.cost.clinchHoldDominant.lac', 0.35, 'mmol/L', '[E]', { min: 0, max: 5 }),
  P('fat.cost.wallPinned.pcr', 4, '0-100', '[E; between bottom and pummel]', { min: 0, max: 50 }),
  P('fat.cost.wallPinned.lac', 0.55, 'mmol/L', '[E]', { min: 0, max: 5 }),
  P('fat.cost.wallPinning.pcr', 3, '0-100', '[E]', { min: 0, max: 50 }),
  P('fat.cost.wallPinning.lac', 0.4, 'mmol/L', '[E]', { min: 0, max: 5 }),
  P('fat.cost.wallWalk.pcr', 8, '0-100', '[E; DAMAGE §4.2 — per stand-up attempt]', { min: 0, max: 50 }),
  P('fat.cost.wallWalk.lac', 0.7, 'mmol/L', '[E; DAMAGE §4.2]', { min: 0, max: 5 }),
  P('fat.cost.groundBottomPressured.pcr', 3, '0-100', '[E; DAMAGE §4.2 — frames + breathing under weight]', { min: 0, max: 50 }),
  P('fat.cost.groundBottomPressured.lac', 0.5, 'mmol/L', '[E; DAMAGE §4.2]', { min: 0, max: 5 }),
  P('fat.cost.groundBottomActive.pcr', 5, '0-100', '[E]', { min: 0, max: 50 }),
  P('fat.cost.groundBottomActive.lac', 0.6, 'mmol/L', '[E]', { min: 0, max: 5 }),
  P('fat.cost.groundTopHold.pcr', 2, '0-100', '[E; DAMAGE §4.2]', { min: 0, max: 50 }),
  P('fat.cost.groundTopHold.lac', 0.25, 'mmol/L', '[E; DAMAGE §4.2]', { min: 0, max: 5 }),
  P('fat.cost.groundTopPassAttempt.pcr', 4, '0-100', '[E]', { min: 0, max: 50 }),
  P('fat.cost.groundTopPassAttempt.lac', 0.4, 'mmol/L', '[E]', { min: 0, max: 5 }),
  P('fat.cost.gnpStrike.pcr', 1.5, '0-100', '[E; DAMAGE §4.2]', { min: 0, max: 50 }),
  P('fat.cost.gnpStrike.lac', 0.1, 'mmol/L', '[E; DAMAGE §4.2]', { min: 0, max: 5 }),
  P('fat.cost.submissionSqueeze.pcr', 9, '0-100', '[E; DAMAGE §4.2; direction from Del Vecchio 2011 E:P 1:2-1:4]', { min: 0, max: 50 }),
  P('fat.cost.submissionSqueeze.lac', 0.9, 'mmol/L', '[E; DAMAGE §4.2]', { min: 0, max: 5 }),
  P('fat.cost.submissionEscape.pcr', 8, '0-100', '[E; DAMAGE §4.2]', { min: 0, max: 50 }),
  P('fat.cost.submissionEscape.lac', 0.8, 'mmol/L', '[E; DAMAGE §4.2]', { min: 0, max: 5 }),
  P('fat.cost.scramble.pcr', 1.2, '0-100', '[E; per second, explosive transitions]', { min: 0, max: 50 }),
  P('fat.cost.scramble.lac', 0.1, 'mmol/L', '[E]', { min: 0, max: 5 }),
  P('fat.cost.movementHighPace.pcr', 0.4, '0-100', '[E; per second above 60% of max speed]', { min: 0, max: 50 }),
  P('fat.cost.movementHighPace.lac', 0.03, 'mmol/L', '[E]', { min: 0, max: 5 }),
  P('fat.cost.movementLowPace.pcr', 0.1, '0-100', '[E; per second]', { min: 0, max: 50 }),
  P('fat.cost.movementLowPace.lac', 0.01, 'mmol/L', '[E]', { min: 0, max: 5 }),
  P('fat.cost.idleStanding.pcr', 0.05, '0-100', '[E; per second]', { min: 0, max: 50 }),
  P('fat.cost.idleStanding.lac', 0.005, 'mmol/L', '[E]', { min: 0, max: 5 }),
  P('fat.flurry.window', 2, 's', '[D: DAMAGE §4.2]', { min: 0.5, max: 10 }),
  P('fat.flurry.count', 4, 'count', '[D: DAMAGE §4.2 — >= 4 strikes within the window]', { min: 2, max: 10 }),
  P('fat.flurry.pcr', 2.0, '0-100', '[D: DAMAGE 12 / 0.9 for a 5-strike flurry minus 5 x 2.5 / 0.15; rounded up, the burst tax is real]', { min: 0, max: 20 }),
  P('fat.flurry.lac', 0.30, 'mmol/L', '[D: DAMAGE §4.2]', { min: 0, max: 5 }),
  P('fat.skillCostSlope', 0.003, 'ratio', '[E; LIT_A §3 Folhes 2023 — RPE per action falls with level; +-15%]', { min: 0, max: 0.02 }),
  P('fat.bodyCostSlope', 0.004, 'ratio', '[E; DAMAGE §2.2 — +4% per 10 structural body points]', { min: 0, max: 0.02 }),
  P('fat.bodyShot.rawThr', 35, '0-100', '[E; DAMAGE §4.2]', POOL),
  P('fat.bodyShot.durS', 60, 's', '[E; DAMAGE §4.2]', { min: 0, max: 300 }),
  P('fat.bodyShot.costMult', 1.10, 'ratio', '[E; DAMAGE §4.2]', RATIO),
  P('fat.bodyShot.aerobicMult', 0.8, 'ratio', '[E; DAMAGE §4.2]', RATIO),
  P('fat.weightCostExp', 0.15, 'ratio', '[E; LIT_A §3 Folhes — HW higher HR after R1]', { min: 0, max: 1 }),
  P('fat.pcrShortfallLacPerUnit', 0.05, 'mmol/L', '[E; an action with no PCr left still executes, on credit]', { min: 0, max: 1 }),
  P('fat.pcrCeil.lacStart', 8, 'mmol/L', '[S: DAMAGE §4.5]', { free: false, min: 0, max: 22 }),
  P('fat.pcrCeil.lacSlope', 1.2, '0-100', '[S: DAMAGE §4.5 — 18 mmol/L gives an 88 ceiling]', { min: 0, max: 5 }),
  P('fat.pcrCeil.dehydPerUnit', 200, '0-100', '[S: DAMAGE §4.7 — -2 pool units per 1% residual]', { min: 0, max: 1000 }),
  P('fat.pcrHalfLifeInRound', 30, 's', '[S: DAMAGE §4.1 — 20-30 s dynamic-exercise half-times; Bogdanis 56.6 s after all-out]', { min: 5, max: 120 }),
  P('fat.intensityGate', 0.3, 'ratio', '[E; PCr only refills below this instantaneous intensity]', PROB),
  P('fat.aerDebtSlope', 0.5, 'ratio', '[E; aerobic debt lengthens the PCr half-time]', { min: 0, max: 3 }),
  P('fat.intensityWindowS', 3, 's', '[E]', { min: 0.5, max: 20 }),
  P('fat.intensityRef', 6, '0-100', '[E; PCr units per window that count as intensity 1.0]', { min: 1, max: 50 }),
  P('fat.lacClearPerMin', 0.4, 'mmol/L', '[S: DAMAGE §4.1 — 0.3-0.5/min at rest]', { min: 0, max: 3 }),
  P('fat.lacActiveMult', 0.5, 'ratio', '[S: DAMAGE §4.1 — clearance halves while working]', RATIO),
  P('fat.lacActiveGate', 0.15, 'ratio', '[E]', PROB),
  P('fat.lacMin', 1.0, 'mmol/L', '[S: DAMAGE §4.1 — resting blood lactate]', { free: false, min: 0, max: 5 }),
  P('fat.lacMax', 22, 'mmol/L', '[S: DAMAGE §1 Amtmann 2008 — post-bout 10-21 mmol/L]', { free: false, min: 5, max: 30 }),
  P('fat.aer.upRate', 0.012, 'ratio', '[E; ~85 s of sustained max effort to full debt]', { min: 0, max: 0.1 }),
  P('fat.aer.downRate', 0.004, 'ratio', '[E; ~4 min of rest to clear]', { min: 0, max: 0.1 }),
  P('fat.f.w.pcr', 0.45, 'ratio', '[S: DAMAGE §4.1]', PROB),
  P('fat.f.w.lac', 0.40, 'ratio', '[S: DAMAGE §4.1]', PROB),
  P('fat.f.w.aer', 0.15, 'ratio', '[S: DAMAGE §4.1]', PROB),
  P('fat.f.w.grapple.pcr', 0.35, 'ratio', '[E; DAMAGE §4.1 — LIT_A §3 Slimani 2017 RPE-lactate r = 0.53 grappling]', PROB),
  P('fat.f.w.grapple.lac', 0.50, 'ratio', '[E; DAMAGE §4.1]', PROB),
  P('fat.f.w.grapple.aer', 0.15, 'ratio', '[E; DAMAGE §4.1]', PROB),
  P('fat.f.lacStart', 4, 'mmol/L', '[S: DAMAGE §4.1]', { min: 0, max: 22 }),
  P('fat.f.lacSpan', 16, 'mmol/L', '[S: DAMAGE §4.1]', { min: 1, max: 30 }),
  P('fat.break.pcrHalfLife', 45, 's', '[S: DAMAGE §4.4 — 60 s break recovers 60% of the deficit at aerobicRate 1]', { min: 5, max: 200 }),
  P('fat.break.ceilCapLac', 14, 'mmol/L', '[S: DAMAGE §4.4]', { min: 0, max: 22 }),
  P('fat.break.ceilCap', 85, '0-100', '[S: DAMAGE §4.4]', POOL),
  P('fat.break.lacDrop', 0.5, 'mmol/L', '[S: DAMAGE §4.4 — negligible, by design]', { min: 0, max: 5 }),
  P('fat.break.aerMult', 0.65, 'ratio', '[S: DAMAGE §4.4]', RATIO),
  P('fat.break.standingPcrMult', 0.85, 'ratio', '[E; a fighter who does not sit down]', RATIO),
  P('fat.break.standingAerMult', 0.8, 'ratio', '[E]', RATIO),
  P('fat.break.breatheAerMult', 0.6, 'ratio', '[E; T3+ corner tells the fighter to breathe]', RATIO),
  P('fat.break.affirmationComposure', 0.1, 'ratio', '[S: MMAI §7.7 CO-4]', PROB),
  P('fat.eff.powerRot.a', 0.25, 'ratio', '[S: DAMAGE §4.3 anchors; Dunn 2022 — rotational punches lose ~2x the jabs force]', PROB),
  P('fat.eff.powerRot.p', 1.1, 'ratio', '[S: DAMAGE §4.3 shape E]', { min: 0.5, max: 3 }),
  P('fat.eff.powerLinear.a', 0.16, 'ratio', '[E; Dunn 2022 ~1/2 of rotational]', PROB),
  P('fat.eff.speed.a', 0.22, 'ratio', '[S: DAMAGE §4.3]', PROB),
  P('fat.eff.output.a', 0.55, 'ratio', '[S: DAMAGE §4.3 — the biggest observed effect]', PROB),
  P('fat.eff.output.p', 1.2, 'ratio', '[S: DAMAGE §4.3 shape E]', { min: 0.5, max: 3 }),
  P('fat.eff.accuracy.a', 0.22, 'ratio', '[S: DAMAGE §4.3]', PROB),
  P('fat.eff.defence.a', 0.55, 'ratio', '[S: DAMAGE §4.3 — defence dies first]', PROB),
  P('fat.eff.defence.p', 1.2, 'ratio', '[S: DAMAGE §4.3 shape E]', { min: 0.5, max: 3 }),
  P('fat.eff.td.a', 0.42, 'ratio', '[S: DAMAGE §4.3]', PROB),
  P('fat.eff.decision.a', 0.42, 'ratio', '[S: DAMAGE §4.3]', PROB),
  P('fat.eff.moveCap.a', 0.25, 'ratio', '[E]', PROB),
  P('fat.bodyAerobicSlope', 0.006, 'ratio', '[E; DAMAGE §2.2 — -6% aerobic refill per 10 body structural]', { min: 0, max: 0.05 }),
  P('fat.dehydAerobicSlope', 4, 'ratio', '[E; DAMAGE §4.7 — 2% residual gives -8%]', { min: 0, max: 20 }),
  P('fat.dump.magnitude.regional', 0.6, 'ratio', '[E; DAMAGE §4.6]', PROB),
  P('fat.dump.magnitude.main', 0.8, 'ratio', '[E; DAMAGE §4.6]', PROB),
  P('fat.dump.magnitude.title', 1.0, 'ratio', '[E; DAMAGE §4.6]', PROB),
  P('fat.dump.magnitude.hostileCrowd', 0.1, 'ratio', '[E; DAMAGE §4.6 — added to the base magnitude]', PROB),
  P('fat.dump.durS', 150, 's', '[E; DAMAGE §4.6 — first 150 s of round 1]', { min: 0, max: 300 }),
  P('fat.dump.costMult', 0.6, 'ratio', '[E; DAMAGE §4.6]', { min: 0, max: 3 }),
  P('fat.dump.decisionMult', 0.2, 'ratio', '[E; DAMAGE §4.6]', PROB),
  P('fat.dump.rushS', 45, 's', '[E; DAMAGE §4.6 — they rush first]', { min: 0, max: 150 }),
  P('fat.dump.rushOutput', 0.15, 'ratio', '[E; DAMAGE §4.6]', PROB),
  P('fat.dump.crashOutput', 0.25, 'ratio', '[E; DAMAGE §4.6 — then the crash]', PROB),
  P('fat.alt.baseM', 500, 'm', '[S: DAMAGE §4.8 — no penalty below this]', { min: 0, max: 3000 }),
  P('fat.alt.vo2PerKm', 0.063, 'ratio', '[S: DAMAGE §4.8 Wehrlin 2006 — VO2max -6.3%/1,000 m]', { free: false, min: 0, max: 0.3 }),
  P('fat.alt.lacPerKm', 0.10, 'ratio', '[E; DAMAGE §4.8]', { min: 0, max: 0.5 }),
  P('fat.alt.acclimMult', 0.5, 'ratio', '[E; DAMAGE §4.8]', PROB),
  P('fat.secondWind.from', 0.7, 'ratio', '[E; DAMAGE §4.5 — psychological, not physiological]', PROB),
  P('fat.secondWind.to', 0.55, 'ratio', '[E; DAMAGE §4.5]', PROB),
  P('fat.secondWind.lowIntensityS', 40, 's', '[E; DAMAGE §4.5]', { min: 0, max: 200 }),
  P('fat.secondWind.gate', 0.3, 'ratio', '[E; DAMAGE §4.5]', PROB),
  P('fat.secondWind.durS', 60, 's', '[E; DAMAGE §4.5 — at most once per round]', { min: 0, max: 300 }),
  P('fat.secondWind.bonus', 0.10, 'ratio', '[E; DAMAGE §4.5 — output and decision quality]', PROB),
  P('fat.grip.perTenS', 1.0, '0-100', '[E; charged by pummelling, squeezing, escaping, wall wrestling]', { min: 0, max: 10 }),
  P('fat.grip.halfLife', 90, 's', '[E]', { min: 10, max: 400 }),
  P('fat.grip.breakDrop', 0.40, 'ratio', '[E]', PROB),
  P('fat.grip.strengthLoss', 0.16, 'ratio', '[S: LIT_A §0.6 — BJJ grip strength -13-16% per match; Nilsson 2002]', { free: false, ...PROB }),
];
