/**
 * Parameters owned by design chapter: docs/design/06_RULES_REFEREE_JUDGING.md
 *
 * Transcribed from that chapter's §4 registry. Values are the **standard**
 * referee preset; the lenient and strict columns live in §2.3.12 and are
 * applied as deltas by `rules/referee.ts` (`STRICTNESS_PRESETS`), because they
 * are a preset table rather than three independent tunables.
 *
 * Ranges in the chapter ("20-60 s", "300-600 s", "8-10 oz") become two
 * parameters or the value the chapter actually uses, never a mid-point guess.
 */
import type { ParamSpec } from './registry';

const S = 'rules' as const;

export const RULES_PARAMS: ParamSpec[] = [
  // ---------------------------------------------------------------- rulesets
  { id: 'rules.mma.roundS', value: 300, unit: 's', tag: '[S: RULES §2.2]', section: S, free: false, note: 'MMA round length' },
  { id: 'rules.mma.breakS', value: 60, unit: 's', tag: '[S: RULES §2.2]', section: S, free: false, note: 'MMA between-rounds rest' },
  { id: 'rules.mma.ncThreshold3', value: 2, unit: 'rounds', tag: '[S: RULES §2.2]', section: S, free: false, note: 'Completed rounds before a 3-round bout can go to a technical decision' },
  { id: 'rules.mma.ncThreshold5', value: 3, unit: 'rounds', tag: '[S: RULES §2.2]', section: S, free: false },
  { id: 'rules.boxing.roundS', value: 180, unit: 's', tag: '[S: RULES §2.3]', section: S, free: false },
  { id: 'rules.boxing.breakS', value: 60, unit: 's', tag: '[S: RULES §2.3]', section: S, free: false },
  { id: 'rules.boxing.ncThreshold', value: 4, unit: 'rounds', tag: '[S: RULES §2.3]', section: S, free: false, note: 'Boxing uses a flat four rounds, not half the distance' },
  { id: 'rules.kb.roundS', value: 180, unit: 's', tag: '[S: RULES §2.4]', section: S, free: false },
  { id: 'rules.kb.breakS', value: 60, unit: 's', tag: '[S: RULES §2.4]', section: S, free: false },
  { id: 'rules.kb.extraBreakS', value: 90, unit: 's', tag: '[S: RULES §2.4]', section: S, free: false, note: 'GLORY sudden-victory round break' },
  { id: 'rules.mt.roundS', value: 180, unit: 's', tag: '[S: RULES §2.5]', section: S, free: false },
  { id: 'rules.mt.breakS', value: 60, unit: 's', tag: '[S: RULES §2.5]', section: S, free: false },
  { id: 'rules.mt.stadiumBreakS', value: 120, unit: 's', tag: '[S: RULES §2.5 (unverified)]', section: S, free: true },
  { id: 'rules.ibjjf.durationWhite', value: 300, unit: 's', tag: '[S: RULES §2.6]', section: S, free: false },
  { id: 'rules.ibjjf.durationBlue', value: 360, unit: 's', tag: '[S: RULES §2.6]', section: S, free: false },
  { id: 'rules.ibjjf.durationPurple', value: 420, unit: 's', tag: '[S: RULES §2.6]', section: S, free: false },
  { id: 'rules.ibjjf.durationBrown', value: 480, unit: 's', tag: '[S: RULES §2.6]', section: S, free: false },
  { id: 'rules.ibjjf.durationBlack', value: 600, unit: 's', tag: '[S: RULES §2.6]', section: S, free: false },
  { id: 'rules.adcc.qualifierS', value: 600, unit: 's', tag: '[S: RULES §2.6]', section: S, free: false },
  { id: 'rules.adcc.qualifierNoPointsS', value: 300, unit: 's', tag: '[S: RULES §2.6]', section: S, free: false, note: 'First half has no positive points' },
  { id: 'rules.adcc.finalS', value: 1200, unit: 's', tag: '[S: RULES §2.6]', section: S, free: false },
  { id: 'rules.adcc.finalNoPointsS', value: 600, unit: 's', tag: '[S: RULES §2.6]', section: S, free: false },
  { id: 'rules.adcc.otMinS', value: 300, unit: 's', tag: '[S: RULES §2.6]', section: S, free: false },
  { id: 'rules.adcc.otMaxS', value: 600, unit: 's', tag: '[S: RULES §2.6]', section: S, free: false },
  { id: 'rules.judo.regulationS', value: 240, unit: 's', tag: '[S: RULES §2.7]', section: S, free: false },
  { id: 'rules.judo.osaekomiYuko', value: 5, unit: 's', tag: '[S: RULES §2.7]', section: S, free: false },
  { id: 'rules.judo.osaekomiWazaAri', value: 10, unit: 's', tag: '[S: RULES §2.7]', section: S, free: false },
  { id: 'rules.judo.osaekomiIppon', value: 20, unit: 's', tag: '[S: RULES §2.7]', section: S, free: false },
  { id: 'rules.judo.attackClockS', value: 45, unit: 's', tag: '[S: RULES §2.7]', section: S, free: true, note: 'IJF SOR text; JUDO §9 says 30 s — chapter resolves to 45' },
  { id: 'rules.grappling.stabiliseS', value: 3, unit: 's', tag: '[S: RULES §2.6]', section: S, free: false, note: 'Position must be held this long to score' },
  { id: 'rules.ibjjf.stallingS', value: 20, unit: 's', tag: '[S: RULES §2.6]', section: S, free: true },
  { id: 'rules.mma.gloveOz', value: 4, unit: 'oz', tag: '[S: RULES §2.2]', section: S, free: false },
  { id: 'rules.boxing.gloveOz', value: 10, unit: 'oz', tag: '[E]', section: S, free: false, note: '8-10 oz by division' },
  { id: 'rules.glory.gloveOzLight', value: 8, unit: 'oz', tag: '[S: RULES §2.4]', section: S, free: false, note: 'Below 65 kg' },
  { id: 'rules.glory.gloveOzHeavy', value: 10, unit: 'oz', tag: '[S: RULES §2.4]', section: S, free: false },
  { id: 'rules.catchWeightGapLb', value: 5, unit: 'lb', tag: '[S: RULES §2.2]', section: S, free: false },
  { id: 'rules.mt.catchKickStepLimit', value: 2, unit: 'count', tag: '[S: RULES §2.5; MTKB §9]', section: S, free: false, note: 'Steps allowed while carrying a caught kick' },
  { id: 'rules.kb.threeKdRound', value: 3, unit: 'count', tag: '[S: RULES §2.4]', section: S, free: false },
  { id: 'rules.kb.fourKdBout', value: 4, unit: 'count', tag: '[S: RULES §2.4]', section: S, free: false },
  { id: 'rules.kb.tournamentKdRound', value: 2, unit: 'count', tag: '[S: RULES §2.4]', section: S, free: false },
  { id: 'rules.kb.tournamentKdBout', value: 3, unit: 'count', tag: '[S: RULES §2.4]', section: S, free: false },
  { id: 'rules.count.mandatory', value: 8, unit: 's', tag: '[S: RULES §6.2]', section: S, free: false },
  { id: 'rules.count.ko', value: 10, unit: 's', tag: '[S: RULES §6.2]', section: S, free: false },
  { id: 'rules.count.outOfRing', value: 20, unit: 's', tag: '[S: RULES §6.2]', section: S, free: false, note: 'Mandatory 18 if he is back sooner' },
  { id: 'rules.foul.recoveryMaxS', value: 300, unit: 's', tag: '[S: RULES §2.2]', section: S, free: false, note: 'Groin/eye recovery clock' },
  { id: 'rules.adcc.recoveryS', value: 120, unit: 's', tag: '[S: RULES §2.6]', section: S, free: false },
  { id: 'rules.foul.deductionIntentional', value: 2, unit: 'count', tag: '[S: RULES §2.2]', section: S, free: false, note: 'Mandatory two points in MMA/boxing/MT' },

  // ----------------------------------------------------------------- referee
  { id: 'ref.strictnessScalar', value: 0.5, unit: '0-1', tag: '[S: DMG §5.1]', section: S, free: true, min: 0, max: 1, note: 'Continuous strictness; 0.2 lenient / 0.8 strict' },
  { id: 'ref.tkoUnansweredGround', value: 4, unit: 'count', tag: '[D: 06 §2.3.3 compromise between RULES 8/5/3 and DMG 3-5]', section: S, free: true, min: 1, max: 12 },
  { id: 'ref.tkoUnansweredStanding', value: 6, unit: 'count', tag: '[D: DMG §5.1 5-8 x strictness scalar]', section: S, free: true, min: 1, max: 16 },
  { id: 'ref.tkoNoDefenceS', value: 2.0, unit: 's', tag: '[S: RULES §5]', section: S, free: true, min: 0.5, max: 6 },
  { id: 'ref.tkoAbsorbed30', value: 18, unit: 'count', tag: '[D: FD #48 18.5 +/- 8.8 strikes in the final 30 s]', section: S, free: true, min: 5, max: 40 },
  { id: 'ref.defenceQualityCeiling', value: 0.30, unit: '0-1', tag: '[E]', section: S, free: true, min: 0, max: 1, note: 'Below this blocked/evaded share, volume counts as repetitive strikes' },
  { id: 'ref.collapseGraceS', value: 6, unit: 's', tag: '[S: DMG §5.1]', section: S, free: true, min: 1, max: 15 },
  { id: 'ref.legCollapseGraceS', value: 5, unit: 's', tag: '[E]', section: S, free: true, min: 1, max: 15 },
  { id: 'ref.secondKdWindowS', value: 10, unit: 's', tag: '[S: DMG §5.1]', section: S, free: true, min: 2, max: 30 },
  { id: 'ref.refReactionS', value: 0.8, unit: 's', tag: '[S: RULES §5]', section: S, free: true, min: 0.1, max: 3 },
  { id: 'ref.travelSPerM', value: 0.4, unit: 's/m', tag: '[E]', section: S, free: true, min: 0, max: 2 },
  { id: 'ref.travelMinS', value: 0.5, unit: 's', tag: '[S: DMG §5.1 positioning 0.5-2.0 s]', section: S, free: false, min: 0, max: 5 },
  { id: 'ref.travelMaxS', value: 2.0, unit: 's', tag: '[S: DMG §5.1 positioning 0.5-2.0 s]', section: S, free: false, min: 0, max: 5 },
  { id: 'ref.pLagTail', value: 0.30, unit: 'probability', tag: '[E]', section: S, free: true, min: 0, max: 1, note: 'Set to 0 for the arcade "no late stoppages" option' },
  { id: 'ref.lagTailMeanS', value: 1.5, unit: 's', tag: '[E]', section: S, free: true, min: 0, max: 20 },
  { id: 'ref.koRecognitionS', value: 1.05, unit: 's', tag: '[D: FD #110 3.5 s total minus the 2.45 s referee model]', section: S, free: true, min: 0, max: 5, note: 'Time for the KO criterion itself to become true after the blow (chapter 05 owns the mechanism)' },
  { id: 'ref.finishingHeadStrikeRateHz', value: 0.74, unit: 'count/s', tag: '[D: FD #49 2.6 extra head strikes over the 3.5 s lag]', section: S, free: true, min: 0, max: 5 },
  { id: 'ref.tapDetectS', value: 0.3, unit: 's', tag: '[E]', section: S, free: true, min: 0, max: 3, note: 'Median; LogNormal sigma 0.4' },
  { id: 'ref.tapDetectSigma', value: 0.4, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0, max: 2 },
  { id: 'ref.locDetectS', value: 1.0, unit: 's', tag: '[E]', section: S, free: true, min: 0, max: 5, note: 'Plus 0.5-1.5 s attacker release lands in the 2.4 s asymptomatic band' },
  { id: 'ref.gaitPassBase', value: 0.85, unit: 'probability', tag: '[E]', section: S, free: true, min: 0, max: 1 },
  { id: 'ref.gaitSlopeLogit', value: 3.0, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 10, note: 'Per 45 acute head points above 45' },
  { id: 'ref.standingEightUnanswered', value: 3, unit: 'count', tag: '[E]', section: S, free: true, min: 1, max: 10 },
  { id: 'ref.neutralCornerS', value: 1.0, unit: 's', tag: '[E]', section: S, free: true, min: 0, max: 5 },
  { id: 'ref.slipRiseCommands', value: 3, unit: 'count', tag: '[E]', section: S, free: true, min: 1, max: 6, note: 'Muay Thai: refusing to rise from a slip after this many commands starts a count' },
  { id: 'ref.standupWarnS', value: 30, unit: 's', tag: '[S: RULES §5]', section: S, free: true, min: 5, max: 120 },
  { id: 'ref.standupS', value: 50, unit: 's', tag: '[S: RULES §5]', section: S, free: true, min: 10, max: 150 },
  { id: 'ref.standupHazardPerS', value: 0.20, unit: 'probability', tag: '[S: 09 §2.7 / BJJ R2]', section: S, free: true, min: 0, max: 1, note: 'Hazard rate once past the threshold, so stand-ups are not a cliff' },
  { id: 'ref.positionMult.dominant', value: 1.5, unit: 'ratio', tag: '[S: BJJ R2]', section: S, free: true, min: 0.1, max: 3 },
  { id: 'ref.positionMult.guard', value: 1.0, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0.1, max: 3 },
  { id: 'ref.positionMult.turtle', value: 0.8, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0.1, max: 3 },
  { id: 'ref.positionMult.standingOver', value: 0.5, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0.1, max: 3 },
  { id: 'ref.positionMult.cageSeated', value: 0.9, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0.1, max: 3 },
  { id: 'ref.effortAttemptCooldownS', value: 5, unit: 's', tag: '[E]', section: S, free: true, min: 0, max: 20, note: 'A strike attempt counts as effort at most once per this window' },
  { id: 'ref.clinchBreakS', value: 25, unit: 's', tag: '[S: RULES §5]', section: S, free: true, min: 3, max: 90 },
  { id: 'ref.clinchBreakOpenMult', value: 0.8, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0.1, max: 2, note: 'Away from the fence the referee breaks sooner' },
  { id: 'ref.kbClinchMaxS', value: 5, unit: 's', tag: '[S: RULES §2.4]', section: S, free: true, min: 0, max: 20 },
  { id: 'ref.boxingBreakS', value: 2.0, unit: 's', tag: '[E]', section: S, free: true, min: 0.2, max: 10 },
  { id: 'ref.mtClinchInactiveS', value: 6, unit: 's', tag: '[S: RULES §3.3 (assumption 5-8)]', section: S, free: true, min: 1, max: 20 },
  { id: 'ref.boxingHoldingWarnings', value: 2, unit: 'count', tag: '[S: RULES §5]', section: S, free: true, min: 0, max: 6 },
  { id: 'ref.timidityWarnS', value: 40, unit: 's', tag: '[S: RULES §5]', section: S, free: true, min: 5, max: 180 },
  { id: 'ref.warningsBeforeDeduction', value: 1, unit: 'count', tag: '[S: RULES §5]', section: S, free: true, min: 0, max: 5 },
  { id: 'ref.pDeductAccidentalRepeat', value: 0.6, unit: 'probability', tag: '[S: RULES §5]', section: S, free: true, min: 0, max: 1 },
  { id: 'ref.dqAfterDeductions', value: 3, unit: 'count', tag: '[S: RULES §5]', section: S, free: true, min: 1, max: 8 },
  { id: 'ref.warningsBeforeIntentional', value: 2, unit: 'count', tag: '[E]', section: S, free: true, min: 0, max: 6, note: 'Repeating a foul this often makes the next one intentional' },
  { id: 'ref.groundedJudgement', value: 0.85, unit: 'probability', tag: '[S: RULES §5]', section: S, free: true, min: 0, max: 1, note: 'Chance the referee reads the grounded status correctly' },
  { id: 'ref.gaitStrictnessLogit', value: 0, unit: 'logit', tag: '[D: from RULES §5 pass rates 0.3/0.5/0.8]', section: S, free: true, min: -3, max: 3 },
  { id: 'ref.pDetectContactFoul', value: 0.85, unit: 'probability', tag: '[E]', section: S, free: true, min: 0, max: 1 },
  { id: 'ref.pDetectFenceGrab', value: 0.85, unit: 'probability', tag: '[E]', section: S, free: true, min: 0, max: 1 },
  { id: 'ref.pDetectBackOfHead', value: 0.80, unit: 'probability', tag: '[E]', section: S, free: true, min: 0, max: 1, note: 'Hard to see from some angles' },
  { id: 'ref.pProtestTimeout', value: 0.05, unit: 'probability', tag: '[E]', section: S, free: true, min: 0, max: 1, note: 'An undetected foul the victim protests loudly enough' },
  { id: 'ref.hornGraceS', value: 0.3, unit: 's', tag: '[E]', section: S, free: true, min: 0, max: 2 },
  { id: 'ref.cutDoctorCall', value: 0.60, unit: '0-1', tag: '[S: RULES §5]', section: S, free: true, min: 0, max: 1, note: 'x3 gives the cut severity that calls the doctor' },
  { id: 'ref.pDoctorStopOrbit', value: 0.80, unit: 'probability', tag: '[S: RULES §5]', section: S, free: true, min: 0, max: 1 },
  { id: 'ref.pDoctorStopVision', value: 0.70, unit: 'probability', tag: '[S: RULES §5]', section: S, free: true, min: 0, max: 1 },
  { id: 'ref.pDoctorStopOther', value: 0.05, unit: 'probability', tag: '[E]', section: S, free: true, min: 0, max: 1 },
  { id: 'ref.doctorExamMinS', value: 20, unit: 's', tag: '[E]', section: S, free: true, min: 1, max: 120 },
  { id: 'ref.doctorExamMaxS', value: 60, unit: 's', tag: '[E]', section: S, free: true, min: 1, max: 180 },
  { id: 'ref.doctorLeniencyRange', value: 0.15, unit: 'ratio', tag: '[S: DMG §5.2]', section: S, free: true, min: 0, max: 0.5 },
  { id: 'ref.doctorVisionStop', value: 0.4, unit: '0-1', tag: '[S: DMG §5.2]', section: S, free: false, min: 0, max: 1 },
  { id: 'ref.roundNearlyOverS', value: 30, unit: 's', tag: '[E]', section: S, free: true, min: 0, max: 120, note: 'Inside this the referee gives the corner the rest period instead of calling time' },
  { id: 'ref.cornerCheckFraction', value: 0.75, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0, max: 1 },
  { id: 'ref.cornerTowelBase', value: 0.5, unit: 'probability', tag: '[E]', section: S, free: true, min: 0, max: 1 },
  { id: 'ref.cornerProtectivenessSlope', value: 2.0, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 8 },
  { id: 'ref.cornerTitlePenalty', value: 1.0, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 5, note: 'Corners are slower to stop a title fight' },
  { id: 'ref.inspectorDelayMinS', value: 5, unit: 's', tag: '[E]', section: S, free: true, min: 0, max: 60 },
  { id: 'ref.inspectorDelayMaxS', value: 15, unit: 's', tag: '[E]', section: S, free: true, min: 0, max: 60 },
  { id: 'ref.mtOutmatchedRatio', value: 4, unit: 'ratio', tag: '[S: RULES §5]', section: S, free: true, min: 1, max: 12 },
  { id: 'ref.bellReadyConsciousness', value: 0.5, unit: '0-1', tag: '[E]', section: S, free: true, min: 0, max: 1 },
  { id: 'ref.judoMateMinS', value: 5, unit: 's', tag: '[S: JUDO §9]', section: S, free: true, min: 1, max: 30 },
  { id: 'ref.judoMateMaxS', value: 10, unit: 's', tag: '[S: JUDO §9]', section: S, free: true, min: 1, max: 40 },
  { id: 'ref.experienceRegionalReactionS', value: 0.3, unit: 's', tag: '[E]', section: S, free: true, min: 0, max: 2 },
  { id: 'ref.experienceRegionalTailP', value: 0.1, unit: 'probability', tag: '[E]', section: S, free: true, min: 0, max: 1 },
  { id: 'ref.experienceEliteReactionS', value: 0.1, unit: 's', tag: '[E]', section: S, free: true, min: 0, max: 2 },

  // ------------------------------------------------------------------- fouls
  { id: 'foul.pEyePokeStraight', value: 0.0018, unit: 'probability', tag: '[D: 0.15 pokes/fight over ~85 straight attempts]', section: S, free: true, min: 0, max: 0.1 },
  { id: 'foul.pEyePokeLongGuardPerS', value: 0.004, unit: 'probability', tag: '[S: INT §2.4 0.3-0.6 %/s]', section: S, free: true, min: 0, max: 0.1 },
  { id: 'foul.pGroinFrontKickKnee', value: 0.006, unit: 'probability', tag: '[S: RULES §3.4]', section: S, free: true, min: 0, max: 0.1 },
  { id: 'foul.pGroinRoundKick', value: 0.003, unit: 'probability', tag: '[S: RULES §3.4]', section: S, free: true, min: 0, max: 0.1 },
  { id: 'foul.pBackOfHeadTurn', value: 0.015, unit: 'probability', tag: '[S: RULES §3.4]', section: S, free: true, min: 0, max: 0.2 },
  { id: 'foul.pBackOfHeadTurtle', value: 0.03, unit: 'probability', tag: '[S: RULES §3.4]', section: S, free: true, min: 0, max: 0.3 },
  { id: 'foul.pGroundedKnee', value: 0.02, unit: 'probability', tag: '[S: RULES §3.4]', section: S, free: true, min: 0, max: 0.3, note: 'Scaled by (1 - ref.groundedJudgement)' },
  { id: 'foul.pGroundedKick', value: 0.02, unit: 'probability', tag: '[S: RULES §3.4]', section: S, free: true, min: 0, max: 0.3 },
  { id: 'foul.pFenceGrabTdd', value: 0.08, unit: 'probability', tag: '[S: RULES §3.4]', section: S, free: true, min: 0, max: 0.5 },
  { id: 'foul.pFenceGrabClinch', value: 0.03, unit: 'probability', tag: '[S: RULES §3.4]', section: S, free: true, min: 0, max: 0.5 },
  { id: 'foul.pFingerInCut', value: 0.002, unit: 'probability', tag: '[S: RULES §3.4]', section: S, free: true, min: 0, max: 0.1 },
  { id: 'foul.pSmallJoint', value: 0.005, unit: 'probability', tag: '[S: RULES §3.4]', section: S, free: true, min: 0, max: 0.1 },
  { id: 'foul.pSpike', value: 0.01, unit: 'probability', tag: '[S: RULES §3.4]', section: S, free: true, min: 0, max: 0.2 },
  { id: 'foul.pAfterBell', value: 0.03, unit: 'probability', tag: '[S: RULES §3.4]', section: S, free: true, min: 0, max: 0.3 },
  { id: 'foul.pHeadClashClinch', value: 0.004, unit: 'probability', tag: '[E]', section: S, free: true, min: 0, max: 0.1, note: 'Per clinch entry; accidental, so not the DQ path' },
  { id: 'foul.pBoxingHolding', value: 0.15, unit: 'probability', tag: '[E]', section: S, free: true, min: 0, max: 1 },
  { id: 'foul.pLowBlow', value: 0.004, unit: 'probability', tag: '[D: 0.12 low blows/fight over ~30 body punches]', section: S, free: true, min: 0, max: 0.1 },
  { id: 'foul.pRabbit', value: 0.01, unit: 'probability', tag: '[E]', section: S, free: true, min: 0, max: 0.2 },
  { id: 'foul.pJudoLegGrabLow', value: 0.05, unit: 'probability', tag: '[E]', section: S, free: true, min: 0, max: 0.5, note: 'Tier 2 and below' },
  { id: 'foul.pJudoLegGrabHigh', value: 0.01, unit: 'probability', tag: '[E]', section: S, free: true, min: 0, max: 0.5 },
  { id: 'foul.tierMult.t0', value: 3.0, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0.1, max: 6 },
  { id: 'foul.tierMult.t1', value: 2.0, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0.1, max: 6 },
  { id: 'foul.tierMult.t2', value: 1.4, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0.1, max: 6 },
  { id: 'foul.tierMult.t3', value: 1.0, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0.1, max: 6 },
  { id: 'foul.tierMult.t4', value: 0.9, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0.1, max: 6 },
  { id: 'foul.tierMult.t5', value: 0.8, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0.1, max: 6 },
  { id: 'foul.rockedFatigueMult', value: 1.5, unit: 'ratio', tag: '[E]', section: S, free: true, min: 1, max: 4 },
  { id: 'foul.dirtyMult', value: 2.0, unit: 'ratio', tag: '[E]', section: S, free: true, min: 1, max: 5 },
  { id: 'foul.intentionalFenceT4', value: 0.2, unit: 'probability', tag: '[E]', section: S, free: true, min: 0, max: 1, note: 'Elite fighters grab the fence deliberately this often' },

  // ------------------------------------------------------------------ judges
  { id: 'judge.w.kd', value: 1.00, unit: 'logit', tag: '[S: LIT_B §3.5]', section: S, free: false, note: 'The unit of the whole judging scale' },
  { id: 'judge.w.rocked', value: 0.45, unit: 'logit', tag: '[S: LIT_B §3.7 range]', section: S, free: true, min: 0, max: 2 },
  { id: 'judge.w.bodyHurt', value: 0.30, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 2 },
  { id: 'judge.w.cut', value: 0.25, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 2 },
  { id: 'judge.w.structuralHead', value: 0.010, unit: 'logit/pt', tag: '[E]', section: S, free: true, min: 0, max: 0.2 },
  { id: 'judge.w.subLocked', value: 0.40, unit: 'logit', tag: '[S: LIT_B §3.5]', section: S, free: false, min: 0, max: 2 },
  { id: 'judge.w.subEarly', value: 0.15, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 2 },
  { id: 'judge.w.reversal', value: 0.26, unit: 'logit', tag: '[S: LIT_B §3.5]', section: S, free: false, min: 0, max: 2 },
  { id: 'judge.w.td', value: 0.34, unit: 'logit', tag: '[S: LIT_B §3.5]', section: S, free: false, min: 0, max: 2 },
  { id: 'judge.w.tdMissed', value: -0.08, unit: 'logit', tag: '[S: LIT_B §3.5]', section: S, free: false, min: -1, max: 0, note: 'A failed takedown costs you the round' },
  { id: 'judge.w.sigHead', value: 0.09, unit: 'logit', tag: '[S: LIT_B §3.5]', section: S, free: false, min: 0, max: 1 },
  { id: 'judge.w.sigBody', value: 0.06, unit: 'logit', tag: '[S: LIT_B §3.5]', section: S, free: false, min: 0, max: 1 },
  { id: 'judge.w.sigLeg', value: 0.055, unit: 'logit', tag: '[S: LIT_B §3.5]', section: S, free: false, min: 0, max: 1 },
  { id: 'judge.w.nonSig', value: 0.013, unit: 'logit', tag: '[S: LIT_B §3.5]', section: S, free: false, min: 0, max: 1 },
  { id: 'judge.w.pass', value: 0.10, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 1 },
  { id: 'judge.w.dominantPosition', value: 0.10, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 1 },
  { id: 'judge.w.controlOffenceS', value: 0.0055, unit: 'logit/s', tag: '[S: LIT_B §3.5]', section: S, free: false, min: 0, max: 0.05 },
  { id: 'judge.w.controlPassiveS', value: 0.0030, unit: 'logit/s', tag: '[E]', section: S, free: true, min: 0, max: 0.05, note: 'Merely holding is worth less than working' },
  { id: 'judge.w.oppDefensiveFraction', value: 0.50, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 2 },
  { id: 'judge.evenThreshold', value: 0.15, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 1, note: 'Below this the judge falls to Plan B' },
  { id: 'judge.planB', value: 0.10, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 1, note: 'Effective aggression' },
  { id: 'judge.planC', value: 0.05, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 1, note: 'Cage/ring control' },
  { id: 'judge.noiseScale', value: 0.26, unit: 'logit', tag: '[E: tuned Phase 9, was 0.32 — engine round margins are narrower in close rounds than the Monte Carlo assumed; split decisions ran 24 % of decisions vs 20 %. Was D: 06 §2.4.3 Monte Carlo, 400k rounds]', section: S, free: true, min: 0.05, max: 1.5 },
  { id: 'judge.noiseScaleBoxing', value: 0.40, unit: 'logit', tag: '[E]', section: S, free: true, min: 0.05, max: 1.5 },
  { id: 'judge.noiseScaleRegional', value: 0.45, unit: 'logit', tag: '[E]', section: S, free: true, min: 0.05, max: 1.5 },
  { id: 'judge.noiseScaleElite', value: 0.30, unit: 'logit', tag: '[E]', section: S, free: true, min: 0.05, max: 1.5 },
  { id: 'judge.noiseToMarginSdRatio', value: 0.22, unit: 'ratio', tag: '[D: 0.32 / 1.44]', section: S, free: false, min: 0, max: 1, note: 'Rescale noiseScale if the engine round-margin SD is not 1.44' },
  { id: 'judge.styleSigma', value: 0.15, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0, max: 1 },
  { id: 'judge.styleSigmaRegional', value: 0.25, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0, max: 1 },
  { id: 'judge.tenEight', value: 6.5, unit: 'logit', tag: '[E: tuned Phase 9, was 2.6 (06 §2.4.3 Monte Carlo) — engine round margins run wider than the Monte Carlo assumed (median |margin| 1.3); 10-8s were 20 %+ of judge-rounds against a real ~4 %]', section: S, free: true, min: 0.5, max: 8 },
  { id: 'judge.propensitySigma', value: 0.25, unit: 'ratio', tag: '[D: 06 §2.4.3 Monte Carlo]', section: S, free: true, min: 0, max: 1 },
  { id: 'judge.tenEightKd', value: 3.2, unit: 'logit', tag: '[E: tuned Phase 9, was 1.2 — see judge.tenEight]', section: S, free: true, min: 0, max: 6, note: 'Perceived margin needed for a 10-8 once damage is significant' },
  { id: 'judge.tenSeven', value: 6.5, unit: 'logit', tag: '[E: tuned Phase 9, was 4.0 — 10-7s were 2.6 % of judge-rounds against a real ~0.1 %]', section: S, free: true, min: 1, max: 12 },
  { id: 'judge.tenEightDamage', value: 5.5, unit: 'logit', tag: '[E: tuned Phase 9, was 2.0 as an absolute total; now the winner-minus-loser damage differential (judges.ts), see judge.tenEight]', section: S, free: true, min: 0, max: 8 },
  { id: 'judge.tenEightDom', value: 0.6, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 4 },
  { id: 'judge.loserOffenceRatio', value: 0.25, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0, max: 1 },
  { id: 'judge.T10', value: 0.05, unit: 'logit', tag: '[D: 06 §2.4.3 Monte Carlo]', section: S, free: true, min: 0, max: 1 },
  { id: 'judge.p1010', value: 0.15, unit: 'probability', tag: '[E: tuned Phase 9, was 0.5 — 10-10 rounds made 3.6 % of fights draws and 7.7 % of decisions majority decisions against a real 0.7 % / 2.5 %; modern judges almost never score 10-10]', section: S, free: true, min: 0, max: 1 },
  { id: 'judge.p1010Boxing', value: 0.3, unit: 'probability', tag: '[E]', section: S, free: true, min: 0, max: 1 },
  { id: 'judge.prevRoundBias', value: 0.15, unit: 'logit', tag: '[D: Gift +3-5 pp round-win / 0.25, LIT_B §3.6]', section: S, free: true, min: 0, max: 1 },
  { id: 'judge.prevRoundCloseOnly', value: 1.0, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 5, note: 'The previous-round bias only applies below this true margin' },
  { id: 'judge.reputationPer10Ranks', value: 0.137, unit: 'logit', tag: '[D: Holmes +0.034 per 10 places / 0.25, LIT_B §3.5]', section: S, free: true, min: 0, max: 1 },
  { id: 'judge.reputationCap', value: 0.40, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 2 },
  { id: 'judge.oddsBias', value: 0.10, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 1, note: 'Per ln(oddsRatio) when no ranks exist' },
  { id: 'judge.homeBiasMma', value: 0.145, unit: 'logit', tag: '[D: Holmes +0.036 / 0.25, LIT_B §3.5]', section: S, free: true, min: 0, max: 1, note: 'Zero when no crowd is present' },
  { id: 'judge.homeBiasBoxing', value: 0.18, unit: 'logit', tag: '[D: MC vs LIT_B §3.9 P(home) = 0.74 over 12 rounds]', section: S, free: true, min: 0, max: 1 },
  { id: 'judge.leadBias', value: 0.15, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 1, note: 'Toward a fighter this judge already has 2 rounds up' },
  { id: 'judge.legacyControlMult', value: 1.5, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0.1, max: 4 },
  { id: 'judge.legacyDamageMult', value: 0.8, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0.1, max: 4 },
  { id: 'judge.legacyTenEightMult', value: 1.3, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0.1, max: 4 },
  { id: 'judge.legacyP1010Mult', value: 3, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0.1, max: 8 },
  { id: 'judge.wholeFightNearFinishBonus', value: 1.0, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 4 },
  { id: 'judge.boxing.wPower', value: 0.10, unit: 'logit', tag: '[E, ratios RULES §4.2]', section: S, free: true, min: 0, max: 1 },
  { id: 'judge.boxing.wJab', value: 0.05, unit: 'logit', tag: '[E, ratios RULES §4.2]', section: S, free: true, min: 0, max: 1 },
  { id: 'judge.boxing.wBody', value: 0.08, unit: 'logit', tag: '[E, ratios RULES §4.2]', section: S, free: true, min: 0, max: 1 },
  { id: 'judge.boxing.wHurt', value: 0.45, unit: 'logit', tag: '[E, ratios RULES §4.2]', section: S, free: true, min: 0, max: 2 },
  { id: 'judge.boxing.wAggr', value: 0.30, unit: 'logit', tag: '[S: RULES §4.2 ordering; size E]', section: S, free: true, min: 0, max: 2 },
  { id: 'judge.boxing.wGeneral', value: 0.20, unit: 'logit', tag: '[S: RULES §4.2 ordering; size E]', section: S, free: true, min: 0, max: 2 },
  { id: 'judge.boxing.wDefence', value: 0.15, unit: 'logit', tag: '[S: RULES §4.2 ordering; size E]', section: S, free: true, min: 0, max: 2, note: 'Boxing scores defence; MMA never does' },
  { id: 'judge.boxing.decisiveMargin', value: 2.6, unit: 'logit', tag: '[E]', section: S, free: true, min: 0.5, max: 8 },
  { id: 'judge.boxing.lastTenSecondsWeight', value: 0.7, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0, max: 1, note: 'Do not let a fighter steal a round with a last-second flurry' },
  { id: 'judge.mt.damageT1', value: 0.5, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 3 },
  { id: 'judge.mt.technique.bodyKick', value: 1.0, unit: 'logit', tag: '[S: RULES §4.4 (assumption)]', section: S, free: true, min: 0, max: 3 },
  { id: 'judge.mt.technique.knee', value: 1.0, unit: 'logit', tag: '[S: RULES §4.4 (assumption)]', section: S, free: true, min: 0, max: 3 },
  { id: 'judge.mt.technique.elbow', value: 0.9, unit: 'logit', tag: '[S: RULES §4.4 (assumption)]', section: S, free: true, min: 0, max: 3 },
  { id: 'judge.mt.technique.punch', value: 0.6, unit: 'logit', tag: '[S: RULES §4.4 (assumption)]', section: S, free: true, min: 0, max: 3 },
  { id: 'judge.mt.technique.lowKick', value: 0.5, unit: 'logit', tag: '[S: RULES §4.4 (assumption)]', section: S, free: true, min: 0, max: 3 },
  { id: 'judge.mt.technique.sweepOffBalance', value: 0.8, unit: 'logit', tag: '[S: RULES §4.4 (assumption)]', section: S, free: true, min: 0, max: 3 },
  { id: 'judge.mt.technique.teepEffective', value: 0.4, unit: 'logit', tag: '[S: RULES §4.4 (assumption)]', section: S, free: true, min: 0, max: 3 },
  { id: 'judge.mt.stadiumRoundWeight1', value: 0.5, unit: 'ratio', tag: '[S: RULES §4.4 (unverified)]', section: S, free: true, min: 0, max: 3 },
  { id: 'judge.mt.stadiumRoundWeight2', value: 0.75, unit: 'ratio', tag: '[S: RULES §4.4 (unverified)]', section: S, free: true, min: 0, max: 3 },
  { id: 'judge.mt.stadiumRoundWeight3', value: 1.25, unit: 'ratio', tag: '[S: RULES §4.4 (unverified)]', section: S, free: true, min: 0, max: 3 },
  { id: 'judge.mt.stadiumRoundWeight4', value: 1.25, unit: 'ratio', tag: '[S: RULES §4.4 (unverified)]', section: S, free: true, min: 0, max: 3 },
  { id: 'judge.mt.stadiumRoundWeight5', value: 0.75, unit: 'ratio', tag: '[S: RULES §4.4 (unverified)]', section: S, free: true, min: 0, max: 3 },
  { id: 'judge.mt.stumble', value: -0.20, unit: 'logit', tag: '[E]', section: S, free: true, min: -2, max: 0 },
  { id: 'judge.mt.catchAndDump', value: 0.30, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 2 },
  { id: 'judge.glory.rocked', value: 0.60, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 3 },
  { id: 'judge.glory.spectacularMult', value: 1.3, unit: 'ratio', tag: '[E]', section: S, free: true, min: 1, max: 3 },
  { id: 'judge.glory.tenEightImpact', value: 0.6, unit: 'logit', tag: '[E]', section: S, free: true, min: 0, max: 3 },

  // ------------------------------------------------------------------ street
  { id: 'street.incapStandS', value: 10, unit: 's', tag: '[E]', section: S, free: true, min: 1, max: 60 },
  { id: 'street.fleeMobilityRatio', value: 0.9, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0, max: 2 },
  { id: 'street.fleeSuccess', value: 0.7, unit: 'probability', tag: '[E]', section: S, free: true, min: 0, max: 1 },
  { id: 'street.surrenderStopP', value: 0.8, unit: 'probability', tag: '[E]', section: S, free: true, min: 0, max: 1, note: 'Per attacker; the design rule is that attacking a surrendered person is never rewarded' },
  { id: 'street.sepHazardPerS', value: 0.010, unit: '1/s', tag: '[E; median ~35 s D]', section: S, free: true, min: 0, max: 1 },
  { id: 'street.sepBystanderMult', value: 0.3, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0, max: 2 },
  { id: 'street.sepStartS', value: 10, unit: 's', tag: '[E]', section: S, free: true, min: 0, max: 60 },
  { id: 'street.weaponHazardPerS', value: 0.001, unit: '1/s', tag: '[E]', section: S, free: true, min: 0, max: 1 },
  { id: 'street.arrivalHazardPerS', value: 0.005, unit: '1/s', tag: '[E]', section: S, free: true, min: 0, max: 1 },

  // -------------------------------------------------------------------- flow
  { id: 'flow.cornerEnterS', value: 5, unit: 's', tag: '[E]', section: S, free: true, min: 0, max: 30 },
  { id: 'flow.doctorStartS', value: 5, unit: 's', tag: '[E]', section: S, free: true, min: 0, max: 30 },
  { id: 'flow.cornerCueWindowStartS', value: 5, unit: 's', tag: '[E]', section: S, free: true, min: 0, max: 60 },
  { id: 'flow.cornerCueWindowEndS', value: 45, unit: 's', tag: '[E]', section: S, free: true, min: 0, max: 120 },
  { id: 'flow.tenSecondWarningS', value: 10, unit: 's', tag: '[E]', section: S, free: false, min: 0, max: 30 },
  { id: 'flow.gauntletBreakS', value: 0, unit: 's', tag: '[E]', section: S, free: true, min: 0, max: 120 },
  { id: 'flow.tagRecoveryMult', value: 1.5, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0.5, max: 3 },
  { id: 'flow.foulTimeoutScale', value: 1.0, unit: 'ratio', tag: '[E]', section: S, free: true, min: 0.05, max: 1, note: 'Playability knob: compresses foul recovery clocks without changing physiology' },
];
