/**
 * GENERATED by scripts/assets/build-rig.mjs — do not edit by hand.
 *
 * The canonical 52-bone skeleton: MPFB2's Mixamo rig (CC0 1.0,
 * github.com/makehumancommunity/mpfb2), converted to three.js coordinates
 * (Y up, character facing +Z, metres). Rest positions are MPFB's default body
 * in its T-pose. Order is parent-before-child and is part of the pose-buffer
 * contract: bone i's local rotation lives at Pose.local[4*i .. 4*i+3].
 */
export interface RigBoneRow {
  name: string;
  /** Index of the parent bone, or -1 for the root (Hips). */
  parent: number;
  /** Rest head (joint) position, model space, metres. */
  head: [number, number, number];
  /** Rest tail position, model space, metres. */
  tail: [number, number, number];
  /** How MPFB locates this joint on the mesh, for re-deriving joints after morphs. */
  headRef: { strategy: string; cube?: string; vertices?: number[] };
  tailRef: { strategy: string; cube?: string; vertices?: number[] };
}

export const RIG_SOURCE = "https://raw.githubusercontent.com/makehumancommunity/mpfb2/master/src/mpfb/data/rigs/standard/rig.mixamo.json";

export const RIG_BONES: readonly RigBoneRow[] = [
 {
  "name": "Hips",
  "parent": -1,
  "head": [ -0.00032, 0.96245, 0.01717],
  "tail": [ 0.00001, 1.06748, 0.02294],
  "headRef": {
   "strategy": "MEAN",
   "vertices": [ 4059, 10997]
  },
  "tailRef": {
   "strategy": "MEAN",
   "vertices": [ 16022, 17349]
  }
 },
 {
  "name": "LeftUpLeg",
  "parent": 0,
  "head": [ 0.1046, 0.91033, 0.00509],
  "tail": [ 0.10252, 0.48847, 0.0367],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-upper-leg"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-knee"
  }
 },
 {
  "name": "RightUpLeg",
  "parent": 0,
  "head": [ -0.1046, 0.91033, 0.00509],
  "tail": [ -0.10155, 0.48848, 0.0367],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-upper-leg"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-knee"
  }
 },
 {
  "name": "Spine",
  "parent": 0,
  "head": [ 0.00001, 1.06748, 0.02294],
  "tail": [ 0, 1.1743, 0.00946],
  "headRef": {
   "strategy": "MEAN",
   "vertices": [ 16022, 17349]
  },
  "tailRef": {
   "strategy": "MEAN",
   "vertices": [ 3991, 10651]
  }
 },
 {
  "name": "Spine1",
  "parent": 3,
  "head": [ 0, 1.1743, 0.00946],
  "tail": [ 0, 1.2984, -0.01942],
  "headRef": {
   "strategy": "MEAN",
   "vertices": [ 3991, 10651]
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-spine-1"
  }
 },
 {
  "name": "Spine2",
  "parent": 4,
  "head": [ 0, 1.2984, -0.01942],
  "tail": [ 0, 1.4785, 0.00545],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-spine-1"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-neck"
  }
 },
 {
  "name": "LeftLeg",
  "parent": 1,
  "head": [ 0.10252, 0.48847, 0.0367],
  "tail": [ 0.0863, 0.06824, 0.01782],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-knee"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-ankle"
  }
 },
 {
  "name": "LeftShoulder",
  "parent": 5,
  "head": [ 0.05742, 1.4388, 0.01475],
  "tail": [ 0.17542, 1.40315, 0.00278],
  "headRef": {
   "strategy": "MEAN",
   "vertices": [ 14055, 18825]
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-shoulder"
  }
 },
 {
  "name": "Neck",
  "parent": 5,
  "head": [ 0, 1.4785, 0.00545],
  "tail": [ -0.00001, 1.53584, 0.00036],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-neck"
  },
  "tailRef": {
   "strategy": "MEAN",
   "vertices": [ 836, 7547]
  }
 },
 {
  "name": "RightLeg",
  "parent": 2,
  "head": [ -0.10155, 0.48848, 0.0367],
  "tail": [ -0.08206, 0.06839, 0.01782],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-knee"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-ankle"
  }
 },
 {
  "name": "RightShoulder",
  "parent": 5,
  "head": [ -0.05931, 1.43959, 0.0136],
  "tail": [ -0.17527, 1.4007, 0.0021],
  "headRef": {
   "strategy": "MEAN",
   "vertices": [ 1493, 15876]
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-shoulder"
  }
 },
 {
  "name": "Head",
  "parent": 8,
  "head": [ 0.00121, 1.5301, 0.02185],
  "tail": [ 0, 1.73319, 0.01963],
  "headRef": {
   "strategy": "MEAN",
   "vertices": [ 823, 7530]
  },
  "tailRef": {
   "strategy": "MEAN",
   "vertices": [ 18875, 19089]
  }
 },
 {
  "name": "LeftArm",
  "parent": 7,
  "head": [ 0.17542, 1.40315, 0.00278],
  "tail": [ 0.42295, 1.39621, -0.02905],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-shoulder"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-elbow"
  }
 },
 {
  "name": "LeftFoot",
  "parent": 6,
  "head": [ 0.0863, 0.06824, 0.01782],
  "tail": [ 0.08196, 0.02194, 0.15713],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-ankle"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-toe-2-1"
  }
 },
 {
  "name": "LeftForeArm",
  "parent": 12,
  "head": [ 0.42295, 1.39621, -0.02905],
  "tail": [ 0.65844, 1.39337, -0.01486],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-elbow"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-hand"
  }
 },
 {
  "name": "LeftHand",
  "parent": 14,
  "head": [ 0.65844, 1.39337, -0.01486],
  "tail": [ 0.7511, 1.38539, -0.0307],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-hand"
  },
  "tailRef": {
   "strategy": "MEAN",
   "vertices": [ 9088, 9891]
  }
 },
 {
  "name": "LeftHandIndex1",
  "parent": 15,
  "head": [ 0.76605, 1.38556, 0.00889],
  "tail": [ 0.79252, 1.38119, 0.00881],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-2-1"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-2-2"
  }
 },
 {
  "name": "LeftHandIndex2",
  "parent": 16,
  "head": [ 0.79252, 1.38119, 0.00881],
  "tail": [ 0.81636, 1.37875, 0.00782],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-2-2"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-2-3"
  }
 },
 {
  "name": "LeftHandIndex3",
  "parent": 17,
  "head": [ 0.81636, 1.37875, 0.00782],
  "tail": [ 0.84348, 1.3724, 0.00688],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-2-3"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-2-4"
  }
 },
 {
  "name": "LeftHandMiddle1",
  "parent": 15,
  "head": [ 0.76444, 1.38999, -0.01812],
  "tail": [ 0.79909, 1.38463, -0.01897],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-3-1"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-3-2"
  }
 },
 {
  "name": "LeftHandMiddle2",
  "parent": 19,
  "head": [ 0.79909, 1.38463, -0.01897],
  "tail": [ 0.8276, 1.38274, -0.01802],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-3-2"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-3-3"
  }
 },
 {
  "name": "LeftHandMiddle3",
  "parent": 20,
  "head": [ 0.8276, 1.38274, -0.01802],
  "tail": [ 0.855, 1.37736, -0.01798],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-3-3"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-3-4"
  }
 },
 {
  "name": "LeftHandPinky1",
  "parent": 15,
  "head": [ 0.74732, 1.38569, -0.05679],
  "tail": [ 0.7694, 1.38444, -0.05811],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-5-1"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-5-2"
  }
 },
 {
  "name": "LeftHandPinky2",
  "parent": 22,
  "head": [ 0.7694, 1.38444, -0.05811],
  "tail": [ 0.78552, 1.3832, -0.05825],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-5-2"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-5-3"
  }
 },
 {
  "name": "LeftHandPinky3",
  "parent": 23,
  "head": [ 0.78552, 1.3832, -0.05825],
  "tail": [ 0.80605, 1.38193, -0.0589],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-5-3"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-5-4"
  }
 },
 {
  "name": "LeftHandRing1",
  "parent": 15,
  "head": [ 0.75788, 1.39044, -0.03804],
  "tail": [ 0.78823, 1.38527, -0.03935],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-4-1"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-4-2"
  }
 },
 {
  "name": "LeftHandRing2",
  "parent": 25,
  "head": [ 0.78823, 1.38527, -0.03935],
  "tail": [ 0.81367, 1.38145, -0.03867],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-4-2"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-4-3"
  }
 },
 {
  "name": "LeftHandRing3",
  "parent": 26,
  "head": [ 0.81367, 1.38145, -0.03867],
  "tail": [ 0.8404, 1.37445, -0.03973],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-4-3"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-4-4"
  }
 },
 {
  "name": "LeftHandThumb1",
  "parent": 15,
  "head": [ 0.69765, 1.38856, 0.0092],
  "tail": [ 0.71057, 1.36669, 0.02855],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-1-1"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-1-2"
  }
 },
 {
  "name": "LeftHandThumb2",
  "parent": 28,
  "head": [ 0.71057, 1.36669, 0.02855],
  "tail": [ 0.73778, 1.34738, 0.046],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-1-2"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-1-3"
  }
 },
 {
  "name": "LeftHandThumb3",
  "parent": 29,
  "head": [ 0.73778, 1.34738, 0.046],
  "tail": [ 0.76095, 1.33105, 0.05165],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-1-3"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-finger-1-4"
  }
 },
 {
  "name": "LeftToeBase",
  "parent": 13,
  "head": [ 0.08196, 0.02194, 0.15713],
  "tail": [ 0.08415, 0.00756, 0.20894],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-l-toe-2-1"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-l-toe-2-4"
  }
 },
 {
  "name": "RightArm",
  "parent": 10,
  "head": [ -0.17527, 1.4007, 0.0021],
  "tail": [ -0.42275, 1.40211, -0.03084],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-shoulder"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-elbow"
  }
 },
 {
  "name": "RightFoot",
  "parent": 9,
  "head": [ -0.08206, 0.06839, 0.01782],
  "tail": [ -0.07737, 0.02212, 0.15713],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-ankle"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-toe-2-1"
  }
 },
 {
  "name": "RightForeArm",
  "parent": 32,
  "head": [ -0.42275, 1.40211, -0.03084],
  "tail": [ -0.65826, 1.4071, -0.01768],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-elbow"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-hand"
  }
 },
 {
  "name": "RightHand",
  "parent": 34,
  "head": [ -0.65826, 1.4071, -0.01768],
  "tail": [ -0.73973, 1.39955, -0.02955],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-hand"
  },
  "tailRef": {
   "strategy": "MEAN",
   "vertices": [ 3115, 3648]
  }
 },
 {
  "name": "RightHandIndex1",
  "parent": 35,
  "head": [ -0.76618, 1.4028, 0.00556],
  "tail": [ -0.79279, 1.39932, 0.00535],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-2-1"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-2-2"
  }
 },
 {
  "name": "RightHandIndex2",
  "parent": 36,
  "head": [ -0.79279, 1.39932, 0.00535],
  "tail": [ -0.81669, 1.39768, 0.00425],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-2-2"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-2-3"
  }
 },
 {
  "name": "RightHandIndex3",
  "parent": 37,
  "head": [ -0.81669, 1.39768, 0.00425],
  "tail": [ -0.844, 1.39224, 0.00317],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-2-3"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-2-4"
  }
 },
 {
  "name": "RightHandMiddle1",
  "parent": 35,
  "head": [ -0.7643, 1.40726, -0.02142],
  "tail": [ -0.7991, 1.40306, -0.02245],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-3-1"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-3-2"
  }
 },
 {
  "name": "RightHandMiddle2",
  "parent": 39,
  "head": [ -0.7991, 1.40306, -0.02245],
  "tail": [ -0.82767, 1.40212, -0.02163],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-3-2"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-3-3"
  }
 },
 {
  "name": "RightHandMiddle3",
  "parent": 40,
  "head": [ -0.82767, 1.40212, -0.02163],
  "tail": [ -0.85523, 1.39766, -0.02172],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-3-3"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-3-4"
  }
 },
 {
  "name": "RightHandPinky1",
  "parent": 35,
  "head": [ -0.74716, 1.40252, -0.06003],
  "tail": [ -0.76926, 1.40201, -0.06145],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-5-1"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-5-2"
  }
 },
 {
  "name": "RightHandPinky2",
  "parent": 42,
  "head": [ -0.76926, 1.40201, -0.06145],
  "tail": [ -0.78541, 1.4013, -0.06166],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-5-2"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-5-3"
  }
 },
 {
  "name": "RightHandPinky3",
  "parent": 43,
  "head": [ -0.78541, 1.4013, -0.06166],
  "tail": [ -0.80597, 1.40073, -0.06242],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-5-3"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-5-4"
  }
 },
 {
  "name": "RightHandRing1",
  "parent": 35,
  "head": [ -0.75764, 1.40756, -0.04132],
  "tail": [ -0.78814, 1.40341, -0.04278],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-4-1"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-4-2"
  }
 },
 {
  "name": "RightHandRing2",
  "parent": 45,
  "head": [ -0.78814, 1.40341, -0.04278],
  "tail": [ -0.8137, 1.40044, -0.04222],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-4-2"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-4-3"
  }
 },
 {
  "name": "RightHandRing3",
  "parent": 46,
  "head": [ -0.8137, 1.40044, -0.04222],
  "tail": [ -0.84064, 1.39433, -0.04342],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-4-3"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-4-4"
  }
 },
 {
  "name": "RightHandThumb1",
  "parent": 35,
  "head": [ -0.69772, 1.40352, 0.00619],
  "tail": [ -0.71145, 1.38203, 0.0254],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-1-1"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-1-2"
  }
 },
 {
  "name": "RightHandThumb2",
  "parent": 48,
  "head": [ -0.71145, 1.38203, 0.0254],
  "tail": [ -0.73936, 1.36359, 0.04267],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-1-2"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-1-3"
  }
 },
 {
  "name": "RightHandThumb3",
  "parent": 49,
  "head": [ -0.73936, 1.36359, 0.04267],
  "tail": [ -0.76309, 1.34802, 0.04816],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-1-3"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-finger-1-4"
  }
 },
 {
  "name": "RightToeBase",
  "parent": 33,
  "head": [ -0.07737, 0.02212, 0.15713],
  "tail": [ -0.07945, 0.00772, 0.20894],
  "headRef": {
   "strategy": "CUBE",
   "cube": "joint-r-toe-2-1"
  },
  "tailRef": {
   "strategy": "CUBE",
   "cube": "joint-r-toe-2-4"
  }
 }
];
